## DATASET FOR GRAPH

In [1]:
import pandas as pd, numpy as np
df = pd.read_csv("/Volumes/SandiskSSD/Developer/AI_Document/Financial_Fraud_Detection_Thesis/data/HI-Small_Trans.csv")

In [2]:
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

In [3]:
df.columns = ['ts','from_bank','from_acct','to_bank','to_acct',
              'amt_recv','cur_recv','amt_paid','cur_paid','fmt','is_laundering']

In [4]:
df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

In [5]:
import pandas as pd, numpy as np
accounts = pd.read_csv("/Volumes/SandiskSSD/Developer/AI_Document/Financial_Fraud_Detection_Thesis/data/HI-Small_accounts.csv")

In [6]:
accounts.columns = ["bank_name", "bank_id", "account_number", "entity_id", "entity_name"]

In [7]:
accounts

,bank_name,bank_id,account_number,entity_id,entity_name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889
...,...,...,...,...,...
518576,France Bank #33,3881,807886B70,80062D160,Sole Proprietorship #22257
518577,National Bank of Topeka,333423,81314C870,800F40230,Sole Proprietorship #4995
518578,Plandor Trust Bank,1467,804ED2270,800CAC4C0,Sole Proprietorship #35326
518579,Sappo Bancorp,2843,801727270,800EFCB40,Sole Proprietorship #3522
518580,Savings Bank of Montpelier,213580,804F6D9F0,800406D60,Partnership #49800

In [8]:
# Join using left_on and right_on
merged_df = pd.merge(df, accounts, left_on="from_acct", right_on="account_number")

In [9]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000EBD30,800D232D0,Partnership #1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0,Sappo Cooperative Bank,3208,8000F4580,8008EEA70,Partnership #2
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0,National Bank of Fort Wayne,3209,8000F4670,800FBB3A0,Partnership #3
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0,National Bank of the East,12,8000F5030,800C0EF20,Sole Proprietorship #1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000F5200,800C3EC10,Partnership #4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0,Crytpo Bank #28,54219,8148A6631,800FE9980,Country #1
5078391,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0,Japan Bank #0,15,8148A8671,800FE9980,Country #1
5078392,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0,Crytpo Bank #41,154365,8148A6771,8004B5CD0,Partnership #38443
5078393,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0,Crytpo Bank #321,256398,8148A6311,8001C0480,Sole Proprietorship #38435
5078394,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0,Crytpo Bank #40,154518,8148A6091,80059FDF0,Partnership #38444

In [10]:
null_summary = pd.DataFrame({
    "null_count": merged_df.isna().sum(),
    "null_rate": merged_df.isna().mean(),
    "null_rate_pct": merged_df.isna().mean() * 100,
    "dtype": merged_df.dtypes
}).sort_values("null_rate", ascending=False)

null_summary

                null_count  null_rate  null_rate_pct    dtype
ts                       0        0.0            0.0      str
from_bank                0        0.0            0.0    int64
from_acct                0        0.0            0.0      str
to_bank                  0        0.0            0.0    int64
to_acct                  0        0.0            0.0      str
amt_recv                 0        0.0            0.0  float64
cur_recv                 0        0.0            0.0      str
amt_paid                 0        0.0            0.0  float64
cur_paid                 0        0.0            0.0      str
fmt                      0        0.0            0.0      str
is_laundering            0        0.0            0.0    int64
bank_name                0        0.0            0.0      str
bank_id                  0        0.0            0.0    int64
account_number           0        0.0            0.0      str
entity_id                0        0.0            0.0      str
entity_name              0        0.0            0.0      str

In [11]:
merged_df["from_acct"].value_counts()

from_acct
100428660    168672
1004286A8    103018
100428978     20497
1004286F0     18663
100428780     17264
              ...
81081A930         1
8113526A0         1
811375C10         1
8148A6631         1
8148A8671         1
Name: count, Length: 496995, dtype: int64

In [12]:
merged_df['is_laundering'].value_counts()

is_laundering
0    5073218
1       5177
Name: count, dtype: int64

In [13]:
from_counts = merged_df["from_acct"].value_counts()

single_from_accts = from_counts[from_counts.eq(1)].index

single_from_acct_rows = merged_df[merged_df["from_acct"].isin(single_from_accts)]

In [14]:
single_from_acct_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0,National Bank of Fort Wayne,3209,8000F4670,800FBB3A0,Partnership #3
31,2022/09/01 00:25,31125,8006AF550,31125,8006AF550,43.440000,US Dollar,43.440000,US Dollar,Reinvestment,0,Bank of Chicago,31125,8006AF550,800E51560,Partnership #15
79,2022/09/01 00:29,2845,8016BC370,2845,8016BC370,17.380000,US Dollar,17.380000,US Dollar,Reinvestment,0,Sea Bank,2845,8016BC370,800DF7B40,Corporation #12
96,2022/09/01 00:03,23885,8018A6110,23885,8018A6110,6.050000,US Dollar,6.050000,US Dollar,Reinvestment,0,Brownstone Bancorp,23885,8018A6110,800F1BE30,Partnership #35
179,2022/09/01 00:27,3233,800106D50,12,800106D00,1384.460000,US Dollar,1384.460000,US Dollar,ACH,0,Bank of Springfield,3233,800106D50,8009E13F0,Partnership #55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078125,2022/09/10 23:30,14,81081A930,43849,81081A570,15754.470000,Shekel,15754.470000,Shekel,ACH,0,China Bank #13,14,81081A930,800E9F100,Partnership #38171
5078186,2022/09/10 23:53,142836,8113526A0,45701,8113526F0,74212.970000,Shekel,74212.970000,Shekel,ACH,0,Israel Bank #37,142836,8113526A0,800E9FE20,Partnership #48033
5078187,2022/09/10 23:44,243614,811375C10,43818,811376B20,6937.590000,Shekel,6937.590000,Shekel,ACH,0,Israel Bank #8,243614,811375C10,800EA5540,Sole Proprietorship #12963
5078390,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0,Crytpo Bank #28,54219,8148A6631,800FE9980,Country #1
5078391,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0,Japan Bank #0,15,8148A8671,800FE9980,Country #1

In [15]:
single_from_acct_rows['is_laundering'].value_counts()

is_laundering
0    152626
1       122
Name: count, dtype: int64

In [16]:
counts = single_from_acct_rows["is_laundering"].value_counts()
ratios = single_from_acct_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

                count     ratio   percent
is_laundering
0              152626  0.999201  99.92013
1                 122  0.000799   0.07987

In [17]:
repeated_rows = merged_df[
    merged_df.groupby("from_acct")["from_acct"].transform("size") > 1
]

In [18]:
repeated_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000EBD30,800D232D0,Partnership #1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0,Sappo Cooperative Bank,3208,8000F4580,8008EEA70,Partnership #2
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0,National Bank of the East,12,8000F5030,800C0EF20,Sole Proprietorship #1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000F5200,800C3EC10,Partnership #4
5,2022/09/01 00:03,1,8000F5AD0,1,8000F5AD0,6162.440000,US Dollar,6162.440000,US Dollar,Reinvestment,0,Arbor Savings Bank,1,8000F5AD0,800FBF300,Partnership #5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078388,2022/09/10 23:43,15,8136C5291,126,81489D161,0.002624,Bitcoin,0.002624,Bitcoin,Bitcoin,0,Japan Bank #0,15,8136C5291,800FE9980,Country #1
5078389,2022/09/10 23:34,15,8136C5291,126,81489D161,0.003010,Bitcoin,0.003010,Bitcoin,Bitcoin,0,Japan Bank #0,15,8136C5291,800FE9980,Country #1
5078392,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0,Crytpo Bank #41,154365,8148A6771,8004B5CD0,Partnership #38443
5078393,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0,Crytpo Bank #321,256398,8148A6311,8001C0480,Sole Proprietorship #38435
5078394,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0,Crytpo Bank #40,154518,8148A6091,80059FDF0,Partnership #38444

In [19]:
repeated_rows['is_laundering'].value_counts()

is_laundering
0    4920592
1       5055
Name: count, dtype: int64

In [20]:
counts = repeated_rows["is_laundering"].value_counts()
ratios = repeated_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

                 count     ratio    percent
is_laundering
0              4920592  0.998974  99.897374
1                 5055  0.001026   0.102626

In [39]:
merged_df['ts']        = pd.to_datetime(merged_df['ts'])
merged_df['time']      = merged_df['ts'].astype('int64') // 10**9         # epoch secs -> time_col

In [78]:
# numeric node features
merged_df['log_paid']  = np.log1p(merged_df['amt_paid'])
merged_df['log_recv']  = np.log1p(merged_df['amt_recv'])
merged_df['amt_ratio'] = (merged_df['amt_recv'] / merged_df['amt_paid'].replace(0,np.nan)).fillna(1)
merged_df['hour']      = merged_df['ts'].dt.hour

In [81]:
for c in ['cur_paid','cur_recv','fmt']:                      # frequency-encode
    merged_df[c+'_FE'] = merged_df[c].map(merged_df[c].value_counts())

In [79]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,bank_name,bank_id,account_number,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,...,National Bank of Laramie,10,8000EBD30,800D232D0,Partnership #1,1661991,8.215639,8.215639,1.0,0
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,...,Sappo Cooperative Bank,3208,8000F4580,8008EEA70,Partnership #2,1661991,0.009950,0.009950,1.0,0
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,...,National Bank of Fort Wayne,3209,8000F4670,800FBB3A0,Partnership #3,1661990,9.594008,9.594008,1.0,0
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,...,National Bank of the East,12,8000F5030,800C0EF20,Sole Proprietorship #1,1661990,7.940217,7.940217,1.0,0
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,...,National Bank of Laramie,10,8000F5200,800C3EC10,Partnership #4,1661990,10.510095,10.510095,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,...,Crytpo Bank #28,54219,8148A6631,800FE9980,Country #1,1662854,0.144081,0.144081,1.0,23
5078391,2022-09-10 23:35:00,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,...,Japan Bank #0,15,8148A8671,800FE9980,Country #1,1662852,0.102672,0.102672,1.0,23
5078392,2022-09-10 23:52:00,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,...,Crytpo Bank #41,154365,8148A6771,8004B5CD0,Partnership #38443,1662853,0.004976,0.004976,1.0,23
5078393,2022-09-10 23:46:00,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,...,Crytpo Bank #321,256398,8148A6311,8001C0480,Sole Proprietorship #38435,1662853,0.037697,0.037697,1.0,23
5078394,2022-09-10 23:37:00,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,...,Crytpo Bank #40,154518,8148A6091,80059FDF0,Partnership #38444,1662853,0.248408,0.248408,1.0,23

In [82]:
bank_name_map = (
    accounts.drop_duplicates("bank_id")
    .set_index("bank_id")["bank_name"]
)

transactions = merged_df.assign(
    from_bank_name=merged_df["from_bank"].map(bank_name_map),
    to_bank_name=merged_df["to_bank"].map(bank_name_map),
)

In [89]:
mask = (
    transactions.groupby("from_acct")["from_bank"]
    .transform("nunique")
    .gt(1)
)

different_source_bank_pairs = (
    transactions.loc[
        mask,
        ["from_acct", "from_bank", "from_bank_name"]
    ]
    .drop_duplicates()
    .sort_values(["from_acct", "from_bank"])
)

different_source_bank_pairs

        from_acct  from_bank             from_bank_name
268181  80A7FD400      27755         Australia Bank #47
927625  80A7FD400      28248         Australia Bank #44
180298  80FA55EF0      13858             Italy Bank #97
923193  80FA55EF0     138832          Germany Bank #908
705555  81211BC00       1490             Italy Bank #95
187423  81211BC00     142574          Germany Bank #945
735514  8135B8250      27444  Savings Bank of Fairfield
116449  8135B8250     221731   National Bank of Danbury

In [90]:
different_source_bank_summary = (
    different_source_bank_pairs.groupby("from_acct")
    .agg(
        bank_count=("from_bank", "size"),
        bank_ids=("from_bank", list),
        bank_names=("from_bank_name", list),
    )
    .reset_index()
)
different_source_bank_summary

,from_acct,bank_count,bank_ids,bank_names
0,80A7FD400,2,"[27755, 28248]","[Australia Bank #47, Australia Bank #44]"
1,80FA55EF0,2,"[13858, 138832]","[Italy Bank #97, Germany Bank #908]"
2,81211BC00,2,"[1490, 142574]","[Italy Bank #95, Germany Bank #945]"
3,8135B8250,2,"[27444, 221731]","[Savings Bank of Fairfield, National Bank of D..."

In [92]:
mask = (
    transactions.groupby("to_acct")["to_bank"]
    .transform("nunique")
    .gt(1)
)

different_to_bank_pairs = (
    transactions.loc[
        mask,
        ["to_acct", "to_bank", "to_bank_name"]
    ]
    .drop_duplicates()
    .sort_values(["to_acct", "to_bank"])
)

different_to_bank_pairs

           to_acct  to_bank               to_bank_name
927625   80A7FDE00    27755         Australia Bank #47
659242   80A7FDE00    28248         Australia Bank #44
923193   80FA56340    13858             Italy Bank #97
889514   80FA56340   138832          Germany Bank #908
1200676  81211BA20     1490             Italy Bank #95
705555   81211BA20   142574          Germany Bank #945
383409   8135B8200    27444  Savings Bank of Fairfield
735514   8135B8200   221731   National Bank of Danbury

In [93]:
different_to_bank_summary = (
    different_to_bank_pairs.groupby("to_acct")
    .agg(
        bank_count=("to_bank", "size"),
        bank_ids=("to_bank", list),
        bank_names=("to_bank_name", list),
    )
    .reset_index()
)
different_to_bank_summary

,to_acct,bank_count,bank_ids,bank_names
0,80A7FDE00,2,"[27755, 28248]","[Australia Bank #47, Australia Bank #44]"
1,80FA56340,2,"[13858, 138832]","[Italy Bank #97, Germany Bank #908]"
2,81211BA20,2,"[1490, 142574]","[Italy Bank #95, Germany Bank #945]"
3,8135B8200,2,"[27444, 221731]","[Savings Bank of Fairfield, National Bank of D..."

In [94]:
merged_df['from_acct'] = merged_df['from_bank'].astype(str)+'_'+merged_df['from_acct'].astype(str)
merged_df['to_acct']   = merged_df['to_bank'].astype(str)+'_'+merged_df['to_acct'].astype(str)

In [95]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour,cur_paid_FE,cur_recv_FE,fmt_FE
0,2022-09-01 00:20:00,10,10_8000EBD30,10,10_8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,...,800D232D0,Partnership #1,1661991,8.215639,8.215639,1.0,0,1895185,1879354,481059
1,2022-09-01 00:20:00,3208,3208_8000F4580,1,1_8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,...,8008EEA70,Partnership #2,1661991,0.009950,0.009950,1.0,0,1895185,1879354,1864333
2,2022-09-01 00:00:00,3209,3209_8000F4670,3209,3209_8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,...,800FBB3A0,Partnership #3,1661990,9.594008,9.594008,1.0,0,1895185,1879354,481059
3,2022-09-01 00:02:00,12,12_8000F5030,12,12_8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,...,800C0EF20,Sole Proprietorship #1,1661990,7.940217,7.940217,1.0,0,1895185,1879354,481059
4,2022-09-01 00:06:00,10,10_8000F5200,10,10_8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,...,800C3EC10,Partnership #4,1661990,10.510095,10.510095,1.0,0,1895185,1879354,481059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,54219_8148A6631,256398,256398_8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662854,0.144081,0.144081,1.0,23,146066,148151,146091
5078391,2022-09-10 23:35:00,15,15_8148A8671,256398,256398_8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662852,0.102672,0.102672,1.0,23,146066,148151,146091
5078392,2022-09-10 23:52:00,154365,154365_8148A6771,256398,256398_8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,...,8004B5CD0,Partnership #38443,1662853,0.004976,0.004976,1.0,23,146066,148151,146091
5078393,2022-09-10 23:46:00,256398,256398_8148A6311,256398,256398_8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,...,8001C0480,Sole Proprietorship #38435,1662853,0.037697,0.037697,1.0,23,146066,148151,146091
5078394,2022-09-10 23:37:00,154518,154518_8148A6091,256398,256398_8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,...,80059FDF0,Partnership #38444,1662853,0.248408,0.248408,1.0,23,146066,148151,146091

In [66]:
equal_mask = np.isclose(
    merged_df["amt_recv"],
    merged_df["amt_paid"],
    rtol=1e-9,
    atol=1e-9,
)

In [67]:
same_currency = merged_df["cur_recv"].eq(merged_df["cur_paid"])

In [68]:
same_currency_rows = merged_df.loc[same_currency]
same_currency_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name,time
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000EBD30,800D232D0,Partnership #1,1661991
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0,Sappo Cooperative Bank,3208,8000F4580,8008EEA70,Partnership #2,1661991
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0,National Bank of Fort Wayne,3209,8000F4670,800FBB3A0,Partnership #3,1661990
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0,National Bank of the East,12,8000F5030,800C0EF20,Sole Proprietorship #1,1661990
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000F5200,800C3EC10,Partnership #4,1661990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0,Crytpo Bank #28,54219,8148A6631,800FE9980,Country #1,1662854
5078391,2022-09-10 23:35:00,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0,Japan Bank #0,15,8148A8671,800FE9980,Country #1,1662852
5078392,2022-09-10 23:52:00,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0,Crytpo Bank #41,154365,8148A6771,8004B5CD0,Partnership #38443,1662853
5078393,2022-09-10 23:46:00,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0,Crytpo Bank #321,256398,8148A6311,8001C0480,Sole Proprietorship #38435,1662853
5078394,2022-09-10 23:37:00,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0,Crytpo Bank #40,154518,8148A6091,80059FDF0,Partnership #38444,1662853

In [69]:
counts = same_currency_rows["is_laundering"].value_counts()
ratios = same_currency_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

                 count     ratio    percent
is_laundering
0              5001048  0.998966  99.896589
1                 5177  0.001034   0.103411

In [70]:
equal_rows_same_currency = merged_df.loc[equal_mask & same_currency].copy()

smaller_rows_same_currency = merged_df.loc[
    (merged_df["amt_recv"] < merged_df["amt_paid"]) & ~equal_mask & same_currency
].copy()

larger_rows_same_currency = merged_df.loc[
    (merged_df["amt_recv"] > merged_df["amt_paid"]) & ~equal_mask & same_currency
].copy()

In [71]:
pd.Series({
    "equal": len(equal_rows_same_currency),
    "amt_recv < amt_paid": len(smaller_rows_same_currency),
    "amt_recv > amt_paid": len(larger_rows_same_currency),
})

equal                  5006225
amt_recv < amt_paid          0
amt_recv > amt_paid          0
dtype: int64

In [72]:
different_currency = merged_df["cur_recv"] != merged_df["cur_paid"]

In [75]:
different_currency_rows = merged_df.loc[different_currency]
different_currency_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name,time
1173,2022-09-01 00:22:00,1362,80030A870,1362,80030A870,52.110000,Euro,61.06,US Dollar,ACH,0,Golden Bancorp,1362,80030A870,800BD25A0,Sole Proprietorship #310,1661991
7156,2022-09-01 00:28:00,11318,800C51010,11318,800C51010,76.060000,Euro,89.12,US Dollar,ACH,0,First Bank of Arkadelphia,11318,800C51010,800EDF0A0,Sole Proprietorship #1898,1661992
7925,2022-09-01 00:12:00,795,800D98770,795,800D98770,17.690000,Australian Dollar,12.52,US Dollar,ACH,0,First Bank of Montpelier,795,800D98770,800C7A8B0,Corporation #1749,1661991
8467,2022-09-01 00:01:00,1047,800E92CF0,1047,800E92CF0,19.430000,Euro,22.77,US Dollar,ACH,0,Flagstone Federal Bank,1047,800E92CF0,800CD3AC0,Partnership #2370,1661990
11529,2022-09-01 00:22:00,11157,80135FFC0,11157,80135FFC0,98.340000,Euro,115.24,US Dollar,ACH,0,Savings Bank of Miami,11157,80135FFC0,800D2E450,Sole Proprietorship #3072,1661991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078217,2022-09-10 23:30:00,23537,803949A90,23537,803949A90,26421.500000,Shekel,7823.96,US Dollar,ACH,0,Capital Trust Bank,23537,803949A90,8002624C0,Partnership #2605,1662852
5078284,2022-09-10 23:59:00,16163,803638A90,16163,803638A90,47517.490000,Saudi Riyal,12667.62,US Dollar,ACH,0,First Bank of Boston,16163,803638A90,80030FE60,Partnership #41679,1662854
5078286,2022-09-10 23:55:00,16163,803638A90,16163,803638A90,11329.850000,Saudi Riyal,3020.41,US Dollar,ACH,0,First Bank of Boston,16163,803638A90,80030FE60,Partnership #41679,1662854
5078366,2022-09-10 23:44:00,215064,808F06E11,215064,808F06E10,0.000006,Bitcoin,0.07,US Dollar,ACH,0,National Bank of Fairfield,215064,808F06E11,800A96D00,Sole Proprietorship #47503,1662853
5078368,2022-09-10 23:45:00,215064,808F06E11,215064,808F06E10,0.000004,Bitcoin,0.05,US Dollar,Wire,0,National Bank of Fairfield,215064,808F06E11,800A96D00,Sole Proprietorship #47503,1662853

In [76]:
counts = different_currency_rows["is_laundering"].value_counts()
ratios = different_currency_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

               count  ratio  percent
is_laundering
0              72170    1.0    100.0

In [ ]:
tx['log_paid'] = np.log1p(tx['amt_paid']); tx['log_recv'] = np.log1p(tx['amt_recv'])
tx['amt_ratio'] = (tx['amt_recv'] / tx['amt_paid'].replace(0, np.nan)).fillna(1.0)
tx['hour'] = tx['ts'].dt.hour; tx['dow'] = tx['ts'].dt.dayofweek
tx['same_cur']   = (tx['cur_recv'] == tx['cur_paid']).astype(np.int8)
tx['cross_bank'] = (tx['from_bank'] != tx['to_bank']).astype(np.int8)
tx['self_loop']  = (tx['from_id'] == tx['to_id']).astype(np.int8)

## DATA FOR LSTM

In [21]:
import pandas as pd, numpy as np
df = pd.read_csv("/Volumes/SandiskSSD/Developer/AI_Document/Financial_Fraud_Detection_Thesis/data/card_transaction_v1.csv")

In [22]:
df

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
0,0,0,2002,9,1,06:21,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
1,0,0,2002,9,1,06:42,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
2,0,0,2002,9,2,06:22,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
3,0,0,2002,9,2,17:45,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,NaN,No
4,0,0,2002,9,3,06:23,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24386895,1999,1,2020,2,27,22:23,$-54.00,Chip Transaction,-5162038175624867091,Merrimack,NH,3054.0,5541,NaN,No
24386896,1999,1,2020,2,27,22:24,$54.00,Chip Transaction,-5162038175624867091,Merrimack,NH,3054.0,5541,NaN,No
24386897,1999,1,2020,2,28,07:43,$59.15,Chip Transaction,2500998799892805156,Merrimack,NH,3054.0,4121,NaN,No
24386898,1999,1,2020,2,28,20:10,$43.12,Chip Transaction,2500998799892805156,Merrimack,NH,3054.0,4121,NaN,No
24386899,1999,1,2020,2,28,23:10,$45.13,Chip Transaction,4751695835751691036,Merrimack,NH,3054.0,5814,NaN,No

In [23]:
df.User.value_counts()

User
486     82355
396     80749
332     70010
262     68089
1249    65644
        ...
457        25
231        21
1367       20
1767       16
1817       15
Name: count, Length: 2000, dtype: int64

In [24]:
user_less_than_14_transactions = df[
    df.groupby("User")["User"].transform("size") < 14
]

In [25]:
user_less_than_14_transactions.shape

(0, 15)

In [26]:
USER_COL = "User"

tmp = df.reset_index(names="original_index").copy()

tmp["run_id"] = tmp[USER_COL].ne(tmp[USER_COL].shift()).cumsum()

continuous_user_runs = (
    tmp.groupby(["run_id", USER_COL], dropna=False)
    .agg(
        start_index=("original_index", "first"),
        end_index=("original_index", "last"),
        continuous_rows=(USER_COL, "size")
    )
    .reset_index()
)

continuous_user_runs

      run_id  User  start_index  end_index  continuous_rows
0          1     0            0      19962            19963
1          2     1        19963      28881             8919
2          3     2        28882      70859            41978
3          4     3        70860      80976            10117
4          5     4        80977      99518            18542
...      ...   ...          ...        ...              ...
1995    1996  1995     24322025   24336737            14713
1996    1997  1996     24336738   24354749            18012
1997    1998  1997     24354750   24376356            21607
1998    1999  1998     24376357   24382138             5782
1999    2000  1999     24382139   24386899             4761

[2000 rows x 5 columns]

In [27]:
user_continuity_summary = (
    continuous_user_runs.groupby(USER_COL, dropna=False)
    .agg(
        num_blocks=("continuous_rows", "size"),
        max_continuous_rows=("continuous_rows", "max"),
        total_rows=("continuous_rows", "sum"),
        avg_continuous_rows=("continuous_rows", "mean")
    )
    .sort_values("max_continuous_rows", ascending=False)
)

user_continuity_summary

      num_blocks  max_continuous_rows  total_rows  avg_continuous_rows
User
486            1                82355       82355              82355.0
396            1                80749       80749              80749.0
332            1                70010       70010              70010.0
262            1                68089       68089              68089.0
1249           1                65644       65644              65644.0
...          ...                  ...         ...                  ...
457            1                   25          25                 25.0
231            1                   21          21                 21.0
1367           1                   20          20                 20.0
1767           1                   16          16                 16.0
1817           1                   15          15                 15.0

[2000 rows x 4 columns]

## SPARKOV DATASET

In [28]:
import pandas as pd, numpy as np
sparkov_df = pd.read_csv("/Volumes/SandiskSSD/Developer/AI_Document/Financial_Fraud_Detection_Thesis/data/Simulated_Credit_Card_Sparkov/fraudTrain.csv")

In [29]:
sparkov_df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,37.7175,-112.4777,258,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,39.2667,-77.5101,100,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,32.9396,-105.8189,899,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,43.3526,-102.5411,1126,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0

In [30]:
sparkov_df["cc_num"].value_counts()

cc_num
4512828414983801773    3123
571365235126           3123
36722699017270         3119
213112402583773        3117
3545109339866548       3113
                       ...
501894933032              7
4975457191020             7
6577777028615915          7
4225628813173670          7
180097223252063           7
Name: count, Length: 983, dtype: int64

In [34]:
USER_COL = "cc_num"

tmp = (
    sparkov_df
    .reset_index(names="original_index")
    .sort_values(["unix_time", "original_index"], kind="stable")
    .reset_index(drop=True)
)

tmp["run_id"] = tmp[USER_COL].ne(tmp[USER_COL].shift()).cumsum()

continuous_user_runs = (
    tmp.groupby("run_id", sort=False)
    .agg(
        cc_num=(USER_COL, "first"),
        start_index=("original_index", "first"),
        end_index=("original_index", "last"),
        start_time=("trans_date_trans_time", "first"),
        end_time=("trans_date_trans_time", "last"),
        consecutive_rows=(USER_COL, "size"),
    )
    .reset_index(drop=True)
)

In [36]:
continuous_user_runs

,cc_num,start_index,end_index,start_time,end_time,consecutive_rows
0,2703186189652095,0,0,2019-01-01 00:00:18,2019-01-01 00:00:18,1
1,630423337322,1,1,2019-01-01 00:00:44,2019-01-01 00:00:44,1
2,38859492057661,2,2,2019-01-01 00:00:51,2019-01-01 00:00:51,1
3,3534093764340240,3,3,2019-01-01 00:01:16,2019-01-01 00:01:16,1
4,375534208663984,4,4,2019-01-01 00:03:06,2019-01-01 00:03:06,1
...,...,...,...,...,...,...
1294712,30263540414123,1296670,1296670,2020-06-21 12:12:08,2020-06-21 12:12:08,1
1294713,6011149206456997,1296671,1296671,2020-06-21 12:12:19,2020-06-21 12:12:19,1
1294714,3514865930894695,1296672,1296672,2020-06-21 12:12:32,2020-06-21 12:12:32,1
1294715,2720012583106919,1296673,1296673,2020-06-21 12:13:36,2020-06-21 12:13:36,1
1294716,4292902571056973207,1296674,1296674,2020-06-21 12:13:37,2020-06-21 12:13:37,1

In [35]:
continuous_user_runs["consecutive_rows"].value_counts().sort_index()

consecutive_rows
1    1292763
2       1950
3          4
Name: count, dtype: int64