## INSPECT DATA

In [45]:
import pandas as pd, numpy as np
df = pd.read_csv("/kaggle/input/datasets/bachhoviet/graph-lstm-datasets/HI-Small_Trans.csv")

In [46]:
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

In [47]:
df.columns = ['ts','from_bank','from_acct','to_bank','to_acct',
              'amt_recv','cur_recv','amt_paid','cur_paid','fmt','is_laundering']

In [48]:
df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

In [49]:
import pandas as pd, numpy as np
accounts = pd.read_csv("/kaggle/input/datasets/bachhoviet/graph-lstm-datasets/HI-Small_accounts.csv")

In [50]:
accounts.columns = ["bank_name", "bank_id", "account_number", "entity_id", "entity_name"]

In [51]:
accounts

,bank_name,bank_id,account_number,entity_id,entity_name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889
...,...,...,...,...,...
518576,France Bank #33,3881,807886B70,80062D160,Sole Proprietorship #22257
518577,National Bank of Topeka,333423,81314C870,800F40230,Sole Proprietorship #4995
518578,Plandor Trust Bank,1467,804ED2270,800CAC4C0,Sole Proprietorship #35326
518579,Sappo Bancorp,2843,801727270,800EFCB40,Sole Proprietorship #3522
518580,Savings Bank of Montpelier,213580,804F6D9F0,800406D60,Partnership #49800

In [52]:
# Join using left_on and right_on
merged_df = pd.merge(df, accounts, left_on="from_acct", right_on="account_number")

In [53]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000EBD30,800D232D0,Partnership #1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0,Sappo Cooperative Bank,3208,8000F4580,8008EEA70,Partnership #2
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0,National Bank of Fort Wayne,3209,8000F4670,800FBB3A0,Partnership #3
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0,National Bank of the East,12,8000F5030,800C0EF20,Sole Proprietorship #1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000F5200,800C3EC10,Partnership #4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0,Crytpo Bank #28,54219,8148A6631,800FE9980,Country #1
5078391,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0,Japan Bank #0,15,8148A8671,800FE9980,Country #1
5078392,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0,Crytpo Bank #41,154365,8148A6771,8004B5CD0,Partnership #38443
5078393,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0,Crytpo Bank #321,256398,8148A6311,8001C0480,Sole Proprietorship #38435
5078394,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0,Crytpo Bank #40,154518,8148A6091,80059FDF0,Partnership #38444

In [54]:
null_summary = pd.DataFrame({
    "null_count": merged_df.isna().sum(),
    "null_rate": merged_df.isna().mean(),
    "null_rate_pct": merged_df.isna().mean() * 100,
    "dtype": merged_df.dtypes
}).sort_values("null_rate", ascending=False)

null_summary

                null_count  null_rate  null_rate_pct    dtype
ts                       0        0.0            0.0   object
from_bank                0        0.0            0.0    int64
from_acct                0        0.0            0.0   object
to_bank                  0        0.0            0.0    int64
to_acct                  0        0.0            0.0   object
amt_recv                 0        0.0            0.0  float64
cur_recv                 0        0.0            0.0   object
amt_paid                 0        0.0            0.0  float64
cur_paid                 0        0.0            0.0   object
fmt                      0        0.0            0.0   object
is_laundering            0        0.0            0.0    int64
bank_name                0        0.0            0.0   object
bank_id                  0        0.0            0.0    int64
account_number           0        0.0            0.0   object
entity_id                0        0.0            0.0   object
entity_name              0        0.0            0.0   object

In [55]:
merged_df["from_acct"].value_counts()

from_acct
100428660    168672
1004286A8    103018
100428978     20497
1004286F0     18663
100428780     17264
              ...
8139A8AC0         1
80E640EA0         1
812C31820         1
8134E7A30         1
8134EE730         1
Name: count, Length: 496995, dtype: int64

In [56]:
merged_df['is_laundering'].value_counts()

is_laundering
0    5073218
1       5177
Name: count, dtype: int64

In [57]:
from_counts = merged_df["from_acct"].value_counts()

single_from_accts = from_counts[from_counts.eq(1)].index

single_from_acct_rows = merged_df[merged_df["from_acct"].isin(single_from_accts)]

In [58]:
single_from_acct_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0,National Bank of Fort Wayne,3209,8000F4670,800FBB3A0,Partnership #3
31,2022/09/01 00:25,31125,8006AF550,31125,8006AF550,43.440000,US Dollar,43.440000,US Dollar,Reinvestment,0,Bank of Chicago,31125,8006AF550,800E51560,Partnership #15
79,2022/09/01 00:29,2845,8016BC370,2845,8016BC370,17.380000,US Dollar,17.380000,US Dollar,Reinvestment,0,Sea Bank,2845,8016BC370,800DF7B40,Corporation #12
96,2022/09/01 00:03,23885,8018A6110,23885,8018A6110,6.050000,US Dollar,6.050000,US Dollar,Reinvestment,0,Brownstone Bancorp,23885,8018A6110,800F1BE30,Partnership #35
179,2022/09/01 00:27,3233,800106D50,12,800106D00,1384.460000,US Dollar,1384.460000,US Dollar,ACH,0,Bank of Springfield,3233,800106D50,8009E13F0,Partnership #55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078125,2022/09/10 23:30,14,81081A930,43849,81081A570,15754.470000,Shekel,15754.470000,Shekel,ACH,0,China Bank #13,14,81081A930,800E9F100,Partnership #38171
5078186,2022/09/10 23:53,142836,8113526A0,45701,8113526F0,74212.970000,Shekel,74212.970000,Shekel,ACH,0,Israel Bank #37,142836,8113526A0,800E9FE20,Partnership #48033
5078187,2022/09/10 23:44,243614,811375C10,43818,811376B20,6937.590000,Shekel,6937.590000,Shekel,ACH,0,Israel Bank #8,243614,811375C10,800EA5540,Sole Proprietorship #12963
5078390,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0,Crytpo Bank #28,54219,8148A6631,800FE9980,Country #1
5078391,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0,Japan Bank #0,15,8148A8671,800FE9980,Country #1

In [59]:
single_from_acct_rows['is_laundering'].value_counts()

is_laundering
0    152626
1       122
Name: count, dtype: int64

In [60]:
counts = single_from_acct_rows["is_laundering"].value_counts()
ratios = single_from_acct_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

                count     ratio   percent
is_laundering
0              152626  0.999201  99.92013
1                 122  0.000799   0.07987

In [61]:
repeated_rows = merged_df[
    merged_df.groupby("from_acct")["from_acct"].transform("size") > 1
]

In [62]:
repeated_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,is_laundering,bank_name,bank_id,account_number,entity_id,entity_name
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000EBD30,800D232D0,Partnership #1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0,Sappo Cooperative Bank,3208,8000F4580,8008EEA70,Partnership #2
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0,National Bank of the East,12,8000F5030,800C0EF20,Sole Proprietorship #1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0,National Bank of Laramie,10,8000F5200,800C3EC10,Partnership #4
5,2022/09/01 00:03,1,8000F5AD0,1,8000F5AD0,6162.440000,US Dollar,6162.440000,US Dollar,Reinvestment,0,Arbor Savings Bank,1,8000F5AD0,800FBF300,Partnership #5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078388,2022/09/10 23:43,15,8136C5291,126,81489D161,0.002624,Bitcoin,0.002624,Bitcoin,Bitcoin,0,Japan Bank #0,15,8136C5291,800FE9980,Country #1
5078389,2022/09/10 23:34,15,8136C5291,126,81489D161,0.003010,Bitcoin,0.003010,Bitcoin,Bitcoin,0,Japan Bank #0,15,8136C5291,800FE9980,Country #1
5078392,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0,Crytpo Bank #41,154365,8148A6771,8004B5CD0,Partnership #38443
5078393,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0,Crytpo Bank #321,256398,8148A6311,8001C0480,Sole Proprietorship #38435
5078394,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0,Crytpo Bank #40,154518,8148A6091,80059FDF0,Partnership #38444

In [63]:
repeated_rows['is_laundering'].value_counts()

is_laundering
0    4920592
1       5055
Name: count, dtype: int64

In [64]:
counts = repeated_rows["is_laundering"].value_counts()
ratios = repeated_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

                 count     ratio    percent
is_laundering
0              4920592  0.998974  99.897374
1                 5055  0.001026   0.102626

In [65]:
merged_df['ts']        = pd.to_datetime(merged_df['ts'])
merged_df['time']      = merged_df['ts'].astype('int64') // 10**9         # epoch secs -> time_col

In [66]:
# numeric node features
merged_df['log_paid']  = np.log1p(merged_df['amt_paid'])
merged_df['log_recv']  = np.log1p(merged_df['amt_recv'])
merged_df['amt_ratio'] = (merged_df['amt_recv'] / merged_df['amt_paid'].replace(0,np.nan)).fillna(1)
merged_df['hour']      = merged_df['ts'].dt.hour

In [67]:
for c in ['cur_paid','cur_recv','fmt']:                      # frequency-encode
    merged_df[c+'_FE'] = merged_df[c].map(merged_df[c].value_counts())

In [68]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour,cur_paid_FE,cur_recv_FE,fmt_FE
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,...,800D232D0,Partnership #1,1661991600,8.215639,8.215639,1.0,0,1895185,1879354,481059
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,...,8008EEA70,Partnership #2,1661991600,0.009950,0.009950,1.0,0,1895185,1879354,1864333
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,...,800FBB3A0,Partnership #3,1661990400,9.594008,9.594008,1.0,0,1895185,1879354,481059
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,...,800C0EF20,Sole Proprietorship #1,1661990520,7.940217,7.940217,1.0,0,1895185,1879354,481059
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,...,800C3EC10,Partnership #4,1661990760,10.510095,10.510095,1.0,0,1895185,1879354,481059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662854220,0.144081,0.144081,1.0,23,146066,148151,146091
5078391,2022-09-10 23:35:00,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662852900,0.102672,0.102672,1.0,23,146066,148151,146091
5078392,2022-09-10 23:52:00,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,...,8004B5CD0,Partnership #38443,1662853920,0.004976,0.004976,1.0,23,146066,148151,146091
5078393,2022-09-10 23:46:00,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,...,8001C0480,Sole Proprietorship #38435,1662853560,0.037697,0.037697,1.0,23,146066,148151,146091
5078394,2022-09-10 23:37:00,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,...,80059FDF0,Partnership #38444,1662853020,0.248408,0.248408,1.0,23,146066,148151,146091

In [69]:
bank_name_map = (
    accounts.drop_duplicates("bank_id")
    .set_index("bank_id")["bank_name"]
)

transactions = merged_df.assign(
    from_bank_name=merged_df["from_bank"].map(bank_name_map),
    to_bank_name=merged_df["to_bank"].map(bank_name_map),
)

In [70]:
mask = (
    transactions.groupby("from_acct")["from_bank"]
    .transform("nunique")
    .gt(1)
)

different_source_bank_pairs = (
    transactions.loc[
        mask,
        ["from_acct", "from_bank", "from_bank_name"]
    ]
    .drop_duplicates()
    .sort_values(["from_acct", "from_bank"])
)

different_source_bank_pairs

        from_acct  from_bank             from_bank_name
268181  80A7FD400      27755         Australia Bank #47
927625  80A7FD400      28248         Australia Bank #44
180298  80FA55EF0      13858             Italy Bank #97
923193  80FA55EF0     138832          Germany Bank #908
705555  81211BC00       1490             Italy Bank #95
187423  81211BC00     142574          Germany Bank #945
735514  8135B8250      27444  Savings Bank of Fairfield
116449  8135B8250     221731   National Bank of Danbury

In [71]:
different_source_bank_summary = (
    different_source_bank_pairs.groupby("from_acct")
    .agg(
        bank_count=("from_bank", "size"),
        bank_ids=("from_bank", list),
        bank_names=("from_bank_name", list),
    )
    .reset_index()
)
different_source_bank_summary

,from_acct,bank_count,bank_ids,bank_names
0,80A7FD400,2,"[27755, 28248]","[Australia Bank #47, Australia Bank #44]"
1,80FA55EF0,2,"[13858, 138832]","[Italy Bank #97, Germany Bank #908]"
2,81211BC00,2,"[1490, 142574]","[Italy Bank #95, Germany Bank #945]"
3,8135B8250,2,"[27444, 221731]","[Savings Bank of Fairfield, National Bank of D..."

In [72]:
mask = (
    transactions.groupby("to_acct")["to_bank"]
    .transform("nunique")
    .gt(1)
)

different_to_bank_pairs = (
    transactions.loc[
        mask,
        ["to_acct", "to_bank", "to_bank_name"]
    ]
    .drop_duplicates()
    .sort_values(["to_acct", "to_bank"])
)

different_to_bank_pairs

           to_acct  to_bank               to_bank_name
927625   80A7FDE00    27755         Australia Bank #47
659242   80A7FDE00    28248         Australia Bank #44
923193   80FA56340    13858             Italy Bank #97
889514   80FA56340   138832          Germany Bank #908
1200676  81211BA20     1490             Italy Bank #95
705555   81211BA20   142574          Germany Bank #945
383409   8135B8200    27444  Savings Bank of Fairfield
735514   8135B8200   221731   National Bank of Danbury

In [73]:
different_to_bank_summary = (
    different_to_bank_pairs.groupby("to_acct")
    .agg(
        bank_count=("to_bank", "size"),
        bank_ids=("to_bank", list),
        bank_names=("to_bank_name", list),
    )
    .reset_index()
)
different_to_bank_summary

,to_acct,bank_count,bank_ids,bank_names
0,80A7FDE00,2,"[27755, 28248]","[Australia Bank #47, Australia Bank #44]"
1,80FA56340,2,"[13858, 138832]","[Italy Bank #97, Germany Bank #908]"
2,81211BA20,2,"[1490, 142574]","[Italy Bank #95, Germany Bank #945]"
3,8135B8200,2,"[27444, 221731]","[Savings Bank of Fairfield, National Bank of D..."

In [74]:
merged_df['from_acct'] = merged_df['from_bank'].astype(str)+'_'+merged_df['from_acct'].astype(str)
merged_df['to_acct']   = merged_df['to_bank'].astype(str)+'_'+merged_df['to_acct'].astype(str)

In [75]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour,cur_paid_FE,cur_recv_FE,fmt_FE
0,2022-09-01 00:20:00,10,10_8000EBD30,10,10_8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,...,800D232D0,Partnership #1,1661991600,8.215639,8.215639,1.0,0,1895185,1879354,481059
1,2022-09-01 00:20:00,3208,3208_8000F4580,1,1_8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,...,8008EEA70,Partnership #2,1661991600,0.009950,0.009950,1.0,0,1895185,1879354,1864333
2,2022-09-01 00:00:00,3209,3209_8000F4670,3209,3209_8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,...,800FBB3A0,Partnership #3,1661990400,9.594008,9.594008,1.0,0,1895185,1879354,481059
3,2022-09-01 00:02:00,12,12_8000F5030,12,12_8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,...,800C0EF20,Sole Proprietorship #1,1661990520,7.940217,7.940217,1.0,0,1895185,1879354,481059
4,2022-09-01 00:06:00,10,10_8000F5200,10,10_8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,...,800C3EC10,Partnership #4,1661990760,10.510095,10.510095,1.0,0,1895185,1879354,481059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,54219_8148A6631,256398,256398_8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662854220,0.144081,0.144081,1.0,23,146066,148151,146091
5078391,2022-09-10 23:35:00,15,15_8148A8671,256398,256398_8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662852900,0.102672,0.102672,1.0,23,146066,148151,146091
5078392,2022-09-10 23:52:00,154365,154365_8148A6771,256398,256398_8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,...,8004B5CD0,Partnership #38443,1662853920,0.004976,0.004976,1.0,23,146066,148151,146091
5078393,2022-09-10 23:46:00,256398,256398_8148A6311,256398,256398_8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,...,8001C0480,Sole Proprietorship #38435,1662853560,0.037697,0.037697,1.0,23,146066,148151,146091
5078394,2022-09-10 23:37:00,154518,154518_8148A6091,256398,256398_8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,...,80059FDF0,Partnership #38444,1662853020,0.248408,0.248408,1.0,23,146066,148151,146091

In [76]:
equal_mask = np.isclose(
    merged_df["amt_recv"],
    merged_df["amt_paid"],
    rtol=1e-9,
    atol=1e-9,
)

In [77]:
same_currency = merged_df["cur_recv"].eq(merged_df["cur_paid"])

In [78]:
same_currency_rows = merged_df.loc[same_currency]
same_currency_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour,cur_paid_FE,cur_recv_FE,fmt_FE
0,2022-09-01 00:20:00,10,10_8000EBD30,10,10_8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,...,800D232D0,Partnership #1,1661991600,8.215639,8.215639,1.0,0,1895185,1879354,481059
1,2022-09-01 00:20:00,3208,3208_8000F4580,1,1_8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,...,8008EEA70,Partnership #2,1661991600,0.009950,0.009950,1.0,0,1895185,1879354,1864333
2,2022-09-01 00:00:00,3209,3209_8000F4670,3209,3209_8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,...,800FBB3A0,Partnership #3,1661990400,9.594008,9.594008,1.0,0,1895185,1879354,481059
3,2022-09-01 00:02:00,12,12_8000F5030,12,12_8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,...,800C0EF20,Sole Proprietorship #1,1661990520,7.940217,7.940217,1.0,0,1895185,1879354,481059
4,2022-09-01 00:06:00,10,10_8000F5200,10,10_8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,...,800C3EC10,Partnership #4,1661990760,10.510095,10.510095,1.0,0,1895185,1879354,481059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,54219_8148A6631,256398,256398_8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662854220,0.144081,0.144081,1.0,23,146066,148151,146091
5078391,2022-09-10 23:35:00,15,15_8148A8671,256398,256398_8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662852900,0.102672,0.102672,1.0,23,146066,148151,146091
5078392,2022-09-10 23:52:00,154365,154365_8148A6771,256398,256398_8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,...,8004B5CD0,Partnership #38443,1662853920,0.004976,0.004976,1.0,23,146066,148151,146091
5078393,2022-09-10 23:46:00,256398,256398_8148A6311,256398,256398_8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,...,8001C0480,Sole Proprietorship #38435,1662853560,0.037697,0.037697,1.0,23,146066,148151,146091
5078394,2022-09-10 23:37:00,154518,154518_8148A6091,256398,256398_8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,...,80059FDF0,Partnership #38444,1662853020,0.248408,0.248408,1.0,23,146066,148151,146091

In [79]:
counts = same_currency_rows["is_laundering"].value_counts()
ratios = same_currency_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

                 count     ratio    percent
is_laundering
0              5001048  0.998966  99.896589
1                 5177  0.001034   0.103411

In [80]:
equal_rows_same_currency = merged_df.loc[equal_mask & same_currency].copy()

smaller_rows_same_currency = merged_df.loc[
    (merged_df["amt_recv"] < merged_df["amt_paid"]) & ~equal_mask & same_currency
].copy()

larger_rows_same_currency = merged_df.loc[
    (merged_df["amt_recv"] > merged_df["amt_paid"]) & ~equal_mask & same_currency
].copy()

In [81]:
pd.Series({
    "equal": len(equal_rows_same_currency),
    "amt_recv < amt_paid": len(smaller_rows_same_currency),
    "amt_recv > amt_paid": len(larger_rows_same_currency),
})

equal                  5006225
amt_recv < amt_paid          0
amt_recv > amt_paid          0
dtype: int64

In [82]:
different_currency = merged_df["cur_recv"] != merged_df["cur_paid"]

In [83]:
different_currency_rows = merged_df.loc[different_currency]
different_currency_rows

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour,cur_paid_FE,cur_recv_FE,fmt_FE
1173,2022-09-01 00:22:00,1362,1362_80030A870,1362,1362_80030A870,52.110000,Euro,61.06,US Dollar,ACH,...,800BD25A0,Sole Proprietorship #310,1661991720,4.128102,3.972365,0.853423,0,1895185,1172042,600802
7156,2022-09-01 00:28:00,11318,11318_800C51010,11318,11318_800C51010,76.060000,Euro,89.12,US Dollar,ACH,...,800EDF0A0,Sole Proprietorship #1898,1661992080,4.501142,4.344584,0.853456,0,1895185,1172042,600802
7925,2022-09-01 00:12:00,795,795_800D98770,795,795_800D98770,17.690000,Australian Dollar,12.52,US Dollar,ACH,...,800C7A8B0,Corporation #1749,1661991120,2.604170,2.927989,1.412939,0,1895185,138523,600802
8467,2022-09-01 00:01:00,1047,1047_800E92CF0,1047,1047_800E92CF0,19.430000,Euro,22.77,US Dollar,ACH,...,800CD3AC0,Partnership #2370,1661990460,3.168424,3.017004,0.853316,0,1895185,1172042,600802
11529,2022-09-01 00:22:00,11157,11157_80135FFC0,11157,11157_80135FFC0,98.340000,Euro,115.24,US Dollar,ACH,...,800D2E450,Sole Proprietorship #3072,1661991720,4.755657,4.598548,0.853350,0,1895185,1172042,600802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078217,2022-09-10 23:30:00,23537,23537_803949A90,23537,23537_803949A90,26421.500000,Shekel,7823.96,US Dollar,ACH,...,8002624C0,Partnership #2605,1662852600,8.965074,10.181971,3.376998,23,1895185,194988,600802
5078284,2022-09-10 23:59:00,16163,16163_803638A90,16163,16163_803638A90,47517.490000,Saudi Riyal,12667.62,US Dollar,ACH,...,80030FE60,Partnership #41679,1662854340,9.446883,10.768874,3.751098,23,1895185,89971,600802
5078286,2022-09-10 23:55:00,16163,16163_803638A90,16163,16163_803638A90,11329.850000,Saudi Riyal,3020.41,US Dollar,ACH,...,80030FE60,Partnership #41679,1662854100,8.013479,9.335284,3.751097,23,1895185,89971,600802
5078366,2022-09-10 23:44:00,215064,215064_808F06E11,215064,215064_808F06E10,0.000006,Bitcoin,0.07,US Dollar,ACH,...,800A96D00,Sole Proprietorship #47503,1662853440,0.067659,0.000006,0.000086,23,1895185,148151,600802
5078368,2022-09-10 23:45:00,215064,215064_808F06E11,215064,215064_808F06E10,0.000004,Bitcoin,0.05,US Dollar,Wire,...,800A96D00,Sole Proprietorship #47503,1662853500,0.048790,0.000004,0.000080,23,1895185,148151,171855

In [84]:
counts = different_currency_rows["is_laundering"].value_counts()
ratios = different_currency_rows["is_laundering"].value_counts(normalize=True)

pd.DataFrame({
    "count": counts,
    "ratio": ratios,
    "percent": ratios * 100
})

               count  ratio  percent
is_laundering
0              72170    1.0    100.0

In [85]:
merged_df

,ts,from_bank,from_acct,to_bank,to_acct,amt_recv,cur_recv,amt_paid,cur_paid,fmt,...,entity_id,entity_name,time,log_paid,log_recv,amt_ratio,hour,cur_paid_FE,cur_recv_FE,fmt_FE
0,2022-09-01 00:20:00,10,10_8000EBD30,10,10_8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,...,800D232D0,Partnership #1,1661991600,8.215639,8.215639,1.0,0,1895185,1879354,481059
1,2022-09-01 00:20:00,3208,3208_8000F4580,1,1_8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,...,8008EEA70,Partnership #2,1661991600,0.009950,0.009950,1.0,0,1895185,1879354,1864333
2,2022-09-01 00:00:00,3209,3209_8000F4670,3209,3209_8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,...,800FBB3A0,Partnership #3,1661990400,9.594008,9.594008,1.0,0,1895185,1879354,481059
3,2022-09-01 00:02:00,12,12_8000F5030,12,12_8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,...,800C0EF20,Sole Proprietorship #1,1661990520,7.940217,7.940217,1.0,0,1895185,1879354,481059
4,2022-09-01 00:06:00,10,10_8000F5200,10,10_8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,...,800C3EC10,Partnership #4,1661990760,10.510095,10.510095,1.0,0,1895185,1879354,481059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078390,2022-09-10 23:57:00,54219,54219_8148A6631,256398,256398_8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662854220,0.144081,0.144081,1.0,23,146066,148151,146091
5078391,2022-09-10 23:35:00,15,15_8148A8671,256398,256398_8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,...,800FE9980,Country #1,1662852900,0.102672,0.102672,1.0,23,146066,148151,146091
5078392,2022-09-10 23:52:00,154365,154365_8148A6771,256398,256398_8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,...,8004B5CD0,Partnership #38443,1662853920,0.004976,0.004976,1.0,23,146066,148151,146091
5078393,2022-09-10 23:46:00,256398,256398_8148A6311,256398,256398_8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,...,8001C0480,Sole Proprietorship #38435,1662853560,0.037697,0.037697,1.0,23,146066,148151,146091
5078394,2022-09-10 23:37:00,154518,154518_8148A6091,256398,256398_8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,...,80059FDF0,Partnership #38444,1662853020,0.248408,0.248408,1.0,23,146066,148151,146091

# ════════════════════════════════════════════════════════════════════
# REFACTORED EXPERIMENT PIPELINE — IBM AML (HI-Small)
# Laundering detection: **Graph vs XGBoost**, in **two graph formulations**
# ════════════════════════════════════════════════════════════════════

Everything **below this divider is a self-contained pipeline**. It re-reads
`HI-Small_Trans.csv` and does its own feature engineering, so it does **not**
depend on any of the exploratory cells above — you can `Run All from here`.

## What gets run

The label `is_laundering` lives on the **transaction**. Every experiment below
predicts that *same* transaction-level label, on the *same rows* and the *same*
temporal train / val / test split, so all numbers are directly comparable.

| # | Experiment | Graph nodes | Runs |
|---|------------|-------------|------|
| 1 | **XGBoost alone** (baseline) | — | once |
| 2 | **Approach A — account graph** (*the appropriate AML graph*) | accounts | graph-alone · graph+XGB |
| 3 | **Approach B — transaction graph** (*your GTAN architecture*) | transactions | graph-alone · graph+XGB |

* **graph alone** = the GNN's own classifier head.
* **graph + XGBoost** = freeze the GNN, feed its node embeddings (+ raw features) to XGBoost.

## Why two graph formulations?

* **Approach A (appropriate for AML).** An AML transaction is literally a
  *directed edge* `from_account → to_account`. The graph that respects the data
  is therefore **nodes = accounts, edges = transactions**, and laundering
  detection becomes **edge classification**. Message passing learns one
  embedding per account from its counterparty neighbourhood; each transaction is
  then scored from its two endpoint embeddings plus its own edge features.

* **Approach B (your GTAN graph).** Your IEEE-Fraud GTAN treats **each
  transaction as a node** and links transactions that share an *identity key*
  (there: `uid`, `card1_addr1`, …). The AML analogue of an identity key is the
  **shared account**: two transactions are linked when they share the same
  sender (`from_id`) or receiver (`to_id`), chained in time exactly like
  `_chain_pairs` in your notebooks. We reuse your `GTANEdge` label-aware
  `TransformerConv`, the 11-dim edge attributes (recency decay / relation flags /
  relation count / cosine), top-k pruning, and weighted neighbour sampling.

## Label-reveal protocol (Approach B)

Your two attached GTAN notebooks differ only in *which node labels are revealed*
to message passing. We default to the **reference-node** protocol (the more
conservative one you leaned toward): in each fold only a fixed fraction of
*training* labels are revealed as "reference" nodes; query-train / val / test
labels stay masked, and a **reference-safe extraction** guarantees a row's own
label is never baked into its own embedding. Set `LABEL_PROTOCOL = "full"` to
instead reveal *all* historical training labels (your other notebook).

## Scale note (important — please read)

HI-Small has **~5.08M transactions** and only **~5.2k laundering (0.10 %)**.
A kNN similarity graph over 5M transaction-nodes is `O(N²)` and infeasible, so
the pipeline **sub-samples**: it keeps **all** laundering rows and down-samples
negatives to `TARGET_N` rows (default **200k**). All three experiments share the
same sample and split, which keeps the comparison fair. Flip
`USE_FULL_DATA = True` to disable sub-sampling — recommended only for Approach A
on a GPU; Approach B's kNN edges auto-disable above `SIM_MAX_NODES` nodes.

## 0 · Setup — install & import

`torch_geometric` and `xgboost` are installed only if missing (quiet no-ops
otherwise). Re-running this cell is safe.

In [86]:
# ===== Setup: install (if missing) + imports =====
# Kaggle: enable a GPU accelerator. torch is pre-installed; we add PyG + its
# sampling backend (pyg-lib / torch-sparse) which NeighborLoader (Approach B) needs.
import importlib, subprocess, sys
import torch
TORCH = torch.__version__
def _has(m):
    try: importlib.import_module(m); return True
    except ImportError: return False

if not _has("torch_geometric"):
    print("installing torch_geometric ...")
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "torch_geometric"])
# NeighborLoader needs a sampling backend; install the wheels matching this torch build
if not (_has("pyg_lib") or _has("torch_sparse")):
    print("installing pyg-lib / torch-scatter / torch-sparse / torch-cluster ...")
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "pyg-lib", "torch-scatter", "torch-sparse", "torch-cluster",
                    "-f", f"https://data.pyg.org/whl/torch-{TORCH}.html"])
if not _has("xgboost"):
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "xgboost"])

import os, gc, math, time, copy, warnings
warnings.filterwarnings("ignore")
import numpy as np, pandas as pd
from torch import nn
import torch.nn.functional as F
from torch_geometric.nn import TransformerConv
from torch_geometric.loader import NeighborLoader
from torch_geometric.data import Data
from sklearn.metrics import roc_auc_score, average_precision_score
import xgboost as xgb

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device, "| torch", torch.__version__, "| xgboost", xgb.__version__)

# sanity: NeighborLoader (Approach B) needs a sampling backend
_backend = "pyg_lib" if _has("pyg_lib") else ("torch_sparse" if _has("torch_sparse") else None)
assert _backend is not None, \
    "NeighborLoader needs pyg-lib or torch-sparse: re-run this cell, then restart the kernel."
print("PyG sampling backend:", _backend)

device: cuda | torch 2.10.0+cu128 | xgboost 3.2.0
PyG sampling backend: pyg_lib

## 1 · Master config

All knobs in one place. The defaults are tuned to **run on CPU** in a reasonable
time; raise `TARGET_N`, epochs, and turn on `USE_SIMILARITY_EDGES` if you have a
GPU.

In [87]:
# ===== Master config =====
DATA_CSV = "/kaggle/input/datasets/bachhoviet/graph-lstm-datasets/HI-Small_Trans.csv"
SEED = 42
np.random.seed(SEED); torch.manual_seed(SEED)

# ---- sampling / temporal split ----
USE_FULL_DATA = False        # True -> keep all ~5.08M rows (heavy; B's kNN auto-off)
TARGET_N      = 500_000      # sub-sample: ALL positives kept + negatives down-sampled to reach this
SPLIT_Q       = (0.70, 0.85) # time quantiles: train <= q70 < val <= q85 < test

# ---- Approach A: account graph (edge classification) ----
A_HIDDEN = 64; A_HEADS = 4; A_LAYERS = 2; A_DROP = 0.2
A_EPOCHS = 40; A_LR = 3e-3; A_WD = 1e-5; A_PATIENCE = 8

# ---- Approach B: GTAN transaction graph (YOUR architecture) ----
LABEL_PROTOCOL       = "reference"          # "reference" (default) or "full"
REF_FRAC             = 0.40                  # fraction of train accounts revealed as reference
REF_SEED             = 123
REFERENCE_OOF_FOLDS  = 5                     # leakage-safe extraction for reference nodes
IDENTITY_COLS        = ["from_id", "to_id"] # AML analogue of uid / card identity keys
EDGE_PER_TRANS       = 4                     # chain depth per shared-account group (small: AML accts are high-degree)
USE_SIMILARITY_EDGES = True                 # kNN cosine edges; auto-off when N > SIM_MAX_NODES
SIM_MAX_NODES        = 500_000; K_SIM = 15; SIM_BATCH = 1024
DECAY_TAUS           = (1.0, 7.0, 30.0)
PRUNE_TOPK           = True; PRUNE_K = 15
USE_WEIGHTED_SAMPLING = True; USE_TEMPORAL_SAMPLING = False
GTAN_HIDDEN = 32; GTAN_HEADS = 4; GTAN_LAYERS = 2; GTAN_DROP = 0.2
GTAN_EPOCHS = 15; GTAN_LR = 3e-4; GTAN_WD = 1e-5
GTAN_BATCH = 2048; GTAN_NEIGH = (16, 10)
GTAN_EARLY_STOP_PATIENCE = 5; GTAN_EARLY_STOP_MIN_DELTA = 1e-4

# ---- XGBoost ----
XGB_PARAMS = dict(max_depth=6, learning_rate=0.05, subsample=0.8, colsample_bytree=0.8,
                  eval_metric="aucpr", tree_method="hist", n_jobs=0)
XGB_ROUNDS = 600; XGB_EARLY = 40

RESULTS = {}   # name -> dict(test_auc, test_ap)
print("config loaded |", "FULL DATA" if USE_FULL_DATA else f"sub-sample TARGET_N={TARGET_N:,}",
      "| label protocol:", LABEL_PROTOCOL)

config loaded | sub-sample TARGET_N=500,000 | label protocol: reference

## 2 · Load + feature engineering (self-contained)

* Re-reads the raw CSV and rebuilds globally-unique account ids
  `from_id = "{bank}_{account}"` (same trick you used in the EDA).
* **Sub-samples** keeping every positive.
* **Temporal split** by timestamp quantiles (train is the earliest 70 %).
* All encodings (currency/format frequency, account degree) are fit on the
  **train split only** → no information leaks from val/test.

Outputs reused by every experiment:
`X_raw` (for XGBoost), `X_std` (standardized, for the GNNs), `y`, the split
masks, `time_arr`, and the account-id columns.

In [88]:
# ===== Load + feature engineering =====
RAW = pd.read_csv(DATA_CSV)
RAW.columns = ['ts','from_bank','from_acct','to_bank','to_acct','amt_recv','cur_recv',
               'amt_paid','cur_paid','fmt','is_laundering']
RAW['ts']   = pd.to_datetime(RAW['ts'])
RAW['time'] = RAW['ts'].astype('int64') // 10**9
RAW['from_id'] = RAW['from_bank'].astype(str) + '_' + RAW['from_acct'].astype(str)
RAW['to_id']   = RAW['to_bank'].astype(str)   + '_' + RAW['to_acct'].astype(str)
print(f"loaded {len(RAW):,} rows | positives = {int(RAW.is_laundering.sum()):,} "
      f"({RAW.is_laundering.mean()*100:.3f}%)")

# ---- sub-sample: keep ALL positives, down-sample negatives ----
if USE_FULL_DATA:
    tx = RAW.sort_values('time').reset_index(drop=True)
else:
    pos = RAW[RAW.is_laundering == 1]
    n_neg = max(0, TARGET_N - len(pos))
    neg = RAW[RAW.is_laundering == 0].sample(n=min(n_neg, int((RAW.is_laundering == 0).sum())),
                                             random_state=SEED)
    tx = pd.concat([pos, neg]).sort_values('time').reset_index(drop=True)
print(f"working set: {len(tx):,} rows | positives = {int(tx.is_laundering.sum()):,} "
      f"({tx.is_laundering.mean()*100:.3f}%)")

# ---- temporal split by time quantiles ----
q_lo, q_hi = tx['time'].quantile(SPLIT_Q[0]), tx['time'].quantile(SPLIT_Q[1])
split   = np.where(tx['time'] <= q_lo, 'train', np.where(tx['time'] <= q_hi, 'val', 'test'))
tr_mask = split == 'train'; va_mask = split == 'val'; te_mask = split == 'test'
y = tx['is_laundering'].to_numpy().astype(np.int64)
for nm, m in [('train', tr_mask), ('val', va_mask), ('test', te_mask)]:
    print(f"  {nm:5s}: {m.sum():>8,} rows | pos = {int(y[m].sum()):>5,} ({y[m].mean()*100:.3f}%)")

# ---- per-transaction features (train-only encodings -> no leakage) ----
tx['log_paid'] = np.log1p(tx['amt_paid']); tx['log_recv'] = np.log1p(tx['amt_recv'])
tx['amt_ratio'] = (tx['amt_recv'] / tx['amt_paid'].replace(0, np.nan)).fillna(1.0)
tx['hour'] = tx['ts'].dt.hour; tx['dow'] = tx['ts'].dt.dayofweek
tx['same_cur']   = (tx['cur_recv'] == tx['cur_paid']).astype(np.int8)
tx['cross_bank'] = (tx['from_bank'] != tx['to_bank']).astype(np.int8)
tx['self_loop']  = (tx['from_id'] == tx['to_id']).astype(np.int8)

def train_freq_encode(col):
    vc = tx.loc[tr_mask, col].value_counts()
    return tx[col].map(vc).fillna(0).astype(np.float32)
for c in ['cur_paid', 'cur_recv', 'fmt']:
    tx[c + '_FE'] = train_freq_encode(c)

out_deg = tx.loc[tr_mask, 'from_id'].value_counts()
in_deg  = tx.loc[tr_mask, 'to_id'].value_counts()
tx['from_out_deg'] = np.log1p(tx['from_id'].map(out_deg).fillna(0)).astype(np.float32)
tx['to_in_deg']    = np.log1p(tx['to_id'].map(in_deg).fillna(0)).astype(np.float32)

FEAT_COLS = ['log_paid','log_recv','amt_ratio','hour','dow','same_cur','cross_bank',
             'self_loop','cur_paid_FE','cur_recv_FE','fmt_FE','from_out_deg','to_in_deg']
X_raw = tx[FEAT_COLS].to_numpy().astype(np.float32)              # for XGBoost (trees: no scaling needed)
mu = X_raw[tr_mask].mean(0); sd = X_raw[tr_mask].std(0) + 1e-6
X_std = ((X_raw - mu) / sd).astype(np.float32)                   # standardized -> GNN node features
time_arr = tx['time'].to_numpy().astype(np.float64)
NF = X_raw.shape[1]
print("feature matrix:", X_raw.shape, "| cols:", FEAT_COLS)

loaded 5,078,345 rows | positives = 5,177 (0.102%)
working set: 500,000 rows | positives = 5,177 (1.035%)
  train:  350,030 rows | pos = 2,862 (0.818%)
  val  :   74,981 rows | pos =   755 (1.007%)
  test :   74,989 rows | pos = 1,560 (2.080%)
feature matrix: (500000, 13) | cols: ['log_paid', 'log_recv', 'amt_ratio', 'hour', 'dow', 'same_cur', 'cross_bank', 'self_loop', 'cur_paid_FE', 'cur_recv_FE', 'fmt_FE', 'from_out_deg', 'to_in_deg']

In [89]:
# ===== small helpers =====
def report(name, y_true, prob):
    auc = roc_auc_score(y_true, prob); ap = average_precision_score(y_true, prob)
    RESULTS[name] = dict(test_auc=float(auc), test_ap=float(ap))
    print(f"  >>> [{name}]  test ROC-AUC = {auc:.4f} | test PR-AUC (AP) = {ap:.4f}")
    return auc, ap

## 3 · Experiment 1 — XGBoost alone (baseline)

Plain gradient-boosted trees on the per-transaction tabular features. Class
imbalance is handled with `scale_pos_weight`; we early-stop on the val split and
report on test. This is the reference every graph model must beat.

In [90]:
# ===== Experiment 1 — XGBoost alone =====
def run_xgb(Xtr, ytr, Xva, yva, Xte, yte, tag):
    spw = float((ytr == 0).sum()) / max(1.0, float((ytr == 1).sum()))
    dtr = xgb.DMatrix(Xtr, label=ytr); dva = xgb.DMatrix(Xva, label=yva); dte = xgb.DMatrix(Xte, label=yte)
    params = {**XGB_PARAMS, 'objective': 'binary:logistic', 'scale_pos_weight': spw, 'seed': SEED}
    bst = xgb.train(params, dtr, num_boost_round=XGB_ROUNDS,
                    evals=[(dtr, 'train'), (dva, 'val')],
                    early_stopping_rounds=XGB_EARLY, verbose_eval=False)
    best = getattr(bst, "best_iteration", XGB_ROUNDS - 1)
    prob = bst.predict(dte, iteration_range=(0, best + 1))
    print(f"  [{tag}] best_iter = {best}")
    return prob, bst

prob, _ = run_xgb(X_raw[tr_mask], y[tr_mask], X_raw[va_mask], y[va_mask],
                  X_raw[te_mask], y[te_mask], "XGBoost-alone")
report("1 · XGBoost alone", y[te_mask], prob)

  [XGBoost-alone] best_iter = 269
  >>> [1 · XGBoost alone]  test ROC-AUC = 0.9730 | test PR-AUC (AP) = 0.5473

(np.float64(0.9730300174841842), np.float64(0.5472549784748909))

## 4 · Approach A — Account-level graph (the appropriate AML graph)

**Nodes = accounts**, **edges = transactions** (`from_id → to_id`).
The message-passing graph is built from **train-period edges only**, so
embeddings for accounts never see a future (val/test) transaction → no temporal
leakage. Each account gets train-only aggregate features (in/out counts &
mean log-amounts). We add reverse edges (with a direction flag) so receivers
also aggregate from senders.

Model: 2 × `TransformerConv` (edge-attribute aware) → account embeddings `H`.
Then an **edge classifier** scores each transaction from
`[H[from], H[to], transaction-features] → logit`.

In [91]:
# ===== Approach A — build the account graph =====
accounts = pd.Index(pd.unique(pd.concat([tx['from_id'], tx['to_id']], ignore_index=True)))
acc2i = {a: i for i, a in enumerate(accounts)}
n_acc = len(accounts)
src_all = tx['from_id'].map(acc2i).to_numpy().astype(np.int64)
dst_all = tx['to_id'].map(acc2i).to_numpy().astype(np.int64)
print(f"account nodes: {n_acc:,} | transaction edges: {len(tx):,}")

# ---- account node features from TRAIN edges only ----
sub = tx[tr_mask]
out_cnt = sub.groupby('from_id').size(); in_cnt = sub.groupby('to_id').size()
out_amt = sub.groupby('from_id')['log_paid'].mean(); in_amt = sub.groupby('to_id')['log_recv'].mean()
node_feat = np.zeros((n_acc, 4), np.float32)
for s, col, tf in [(out_cnt, 0, True), (in_cnt, 1, True), (out_amt, 2, False), (in_amt, 3, False)]:
    idx = np.array([acc2i[a] for a in s.index], dtype=np.int64)
    node_feat[idx, col] = np.log1p(s.to_numpy()) if tf else s.to_numpy()
node_feat = ((node_feat - node_feat.mean(0)) / (node_feat.std(0) + 1e-6)).astype(np.float32)

# ---- message-passing graph = TRAIN edges, bidirectional (+ direction flag on edge_attr) ----
tr_e = np.where(tr_mask)[0]
ei_fwd = np.stack([src_all[tr_e], dst_all[tr_e]])
ei_rev = np.stack([dst_all[tr_e], src_all[tr_e]])
ea_fwd = np.concatenate([X_std[tr_e], np.ones((len(tr_e), 1), np.float32)], 1)
ea_rev = np.concatenate([X_std[tr_e], np.zeros((len(tr_e), 1), np.float32)], 1)
mp_edge_index = torch.tensor(np.concatenate([ei_fwd, ei_rev], 1), dtype=torch.long)
mp_edge_attr  = torch.tensor(np.concatenate([ea_fwd, ea_rev], 0), dtype=torch.float32)
print(f"message-passing edges (incl. reverse): {mp_edge_index.shape[1]:,} | "
      f"node_feat {node_feat.shape} | edge_attr dim {mp_edge_attr.shape[1]}")

account nodes: 265,502 | transaction edges: 500,000
message-passing edges (incl. reverse): 700,060 | node_feat (265502, 4) | edge_attr dim 14

In [92]:
# ===== Approach A — model =====
class AccountGNN(nn.Module):
    def __init__(self, in_node, mp_edge_dim, txn_feat_dim,
                 hidden=A_HIDDEN, heads=A_HEADS, layers=A_LAYERS, drop=A_DROP):
        super().__init__()
        self.convs = nn.ModuleList(); self.norms = nn.ModuleList()
        dim = in_node
        for _ in range(layers):
            self.convs.append(TransformerConv(dim, hidden, heads=heads, concat=True,
                                              beta=True, dropout=drop, edge_dim=mp_edge_dim))
            self.norms.append(nn.LayerNorm(hidden * heads))
            dim = hidden * heads
        self.act = nn.PReLU(); self.drop = nn.Dropout(drop)
        self.emb_dim = dim
        self.edge_head = nn.Sequential(
            nn.Linear(2 * dim + txn_feat_dim, dim), nn.BatchNorm1d(dim), nn.PReLU(),
            nn.Dropout(drop), nn.Linear(dim, 1),
        )
    def encode(self, x, edge_index, edge_attr):
        h = x
        for conv, norm in zip(self.convs, self.norms):
            h = self.drop(self.act(norm(conv(h, edge_index, edge_attr=edge_attr))))
        return h
    def classify(self, H, src, dst, txn_feat):
        return self.edge_head(torch.cat([H[src], H[dst], txn_feat], dim=1)).squeeze(-1)

print("AccountGNN defined")

AccountGNN defined

In [93]:
# ===== Approach A — train (graph alone) =====
def train_account_gnn():
    torch.manual_seed(SEED)
    model = AccountGNN(node_feat.shape[1], mp_edge_attr.shape[1], NF).to(device)
    x  = torch.tensor(node_feat, device=device)
    ei = mp_edge_index.to(device); ea = mp_edge_attr.to(device)
    src_t = torch.tensor(src_all, device=device); dst_t = torch.tensor(dst_all, device=device)
    Xe = torch.tensor(X_std, device=device); yt = torch.tensor(y, device=device, dtype=torch.float32)
    tr_i = torch.tensor(np.where(tr_mask)[0], device=device)
    va_i = torch.tensor(np.where(va_mask)[0], device=device)
    te_i = torch.tensor(np.where(te_mask)[0], device=device)

    pos = float(y[tr_mask].sum()); neg = float((~(y[tr_mask] == 1)).sum())
    pw = torch.tensor([np.sqrt(neg / max(pos, 1.0))], device=device)
    loss_fn = nn.BCEWithLogitsLoss(pos_weight=pw)
    opt = torch.optim.AdamW(model.parameters(), lr=A_LR, weight_decay=A_WD)

    best_auc, best_state, bad = -1.0, None, 0
    for ep in range(1, A_EPOCHS + 1):
        model.train(); opt.zero_grad()
        H = model.encode(x, ei, ea)
        loss = loss_fn(model.classify(H, src_t[tr_i], dst_t[tr_i], Xe[tr_i]), yt[tr_i])
        loss.backward(); nn.utils.clip_grad_norm_(model.parameters(), 2.0); opt.step()
        model.eval()
        with torch.no_grad():
            H = model.encode(x, ei, ea)
            vp = torch.sigmoid(model.classify(H, src_t[va_i], dst_t[va_i], Xe[va_i])).cpu().numpy()
        va_auc = roc_auc_score(y[va_mask], vp)
        print(f"   ep {ep:2d}/{A_EPOCHS}  loss={loss.item():.4f}  val_auc={va_auc:.4f}")
        if va_auc > best_auc:
            best_auc, best_state, bad = va_auc, copy.deepcopy(model.state_dict()), 0
        else:
            bad += 1
            if bad >= A_PATIENCE:
                print(f"   early stop at epoch {ep}"); break
    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        H = model.encode(x, ei, ea)
        tp = torch.sigmoid(model.classify(H, src_t[te_i], dst_t[te_i], Xe[te_i])).cpu().numpy()
        H_np = H.detach().cpu().numpy()
    return tp, H_np

A_test_prob, A_H = train_account_gnn()
report("2a · Account-graph alone", y[te_mask], A_test_prob)

   ep  1/40  loss=0.7878  val_auc=0.5436
   ep  2/40  loss=0.9136  val_auc=0.6072
   ep  3/40  loss=0.6672  val_auc=0.7161
   ep  4/40  loss=0.5148  val_auc=0.6911
   ep  5/40  loss=0.4560  val_auc=0.7377
   ep  6/40  loss=0.3950  val_auc=0.7701
   ep  7/40  loss=0.3470  val_auc=0.7783
   ep  8/40  loss=0.3152  val_auc=0.7893
   ep  9/40  loss=0.2930  val_auc=0.7949
   ep 10/40  loss=0.2792  val_auc=0.7989
   ep 11/40  loss=0.2638  val_auc=0.7999
   ep 12/40  loss=0.2490  val_auc=0.8016
   ep 13/40  loss=0.2375  val_auc=0.8024
   ep 14/40  loss=0.2329  val_auc=0.8076
   ep 15/40  loss=0.2250  val_auc=0.8122
   ep 16/40  loss=0.2216  val_auc=0.8192
   ep 17/40  loss=0.2166  val_auc=0.8253
   ep 18/40  loss=0.2133  val_auc=0.8282
   ep 19/40  loss=0.2124  val_auc=0.8246
   ep 20/40  loss=0.2042  val_auc=0.8211
   ep 21/40  loss=0.2063  val_auc=0.8239
   ep 22/40  loss=0.2022  val_auc=0.8292
   ep 23/40  loss=0.2000  val_auc=0.8353
   ep 24/40  loss=0.1957  val_auc=0.8397
   ep 25/40  loss=0.1926  val_auc=0.8412
   ep 26/40  loss=0.1919  val_auc=0.8395
   ep 27/40  loss=0.1882  val_auc=0.8380
   ep 28/40  loss=0.1916  val_auc=0.8382
   ep 29/40  loss=0.1886  val_auc=0.8413
   ep 30/40  loss=0.1857  val_auc=0.8473
   ep 31/40  loss=0.1851  val_auc=0.8537
   ep 32/40  loss=0.1823  val_auc=0.8570
   ep 33/40  loss=0.1793  val_auc=0.8562
   ep 34/40  loss=0.1805  val_auc=0.8531
   ep 35/40  loss=0.1783  val_auc=0.8514
   ep 36/40  loss=0.1779  val_auc=0.8527
   ep 37/40  loss=0.1777  val_auc=0.8562
   ep 38/40  loss=0.1755  val_auc=0.8602
   ep 39/40  loss=0.1741  val_auc=0.8648
   ep 40/40  loss=0.1720  val_auc=0.8690
  >>> [2a · Account-graph alone]  test ROC-AUC = 0.8476 | test PR-AUC (AP) = 0.1506

(np.float64(0.8475745888842213), np.float64(0.15055047315382275))

### 4b · Approach A — Graph + XGBoost

Freeze the learned account embeddings `H`. For every transaction build
`[H[from], H[to], raw transaction features]` and hand it to XGBoost. This tests
whether the structural account embeddings add signal on top of the tabular
baseline.

In [94]:
# ===== Approach A — graph embeddings + XGBoost =====
def A_edge_features(idx):
    return np.concatenate([A_H[src_all[idx]], A_H[dst_all[idx]], X_raw[idx]], axis=1).astype(np.float32)

A_tr = A_edge_features(np.where(tr_mask)[0]); A_va = A_edge_features(np.where(va_mask)[0])
A_te = A_edge_features(np.where(te_mask)[0])
print("Approach-A XGB feature dim:", A_tr.shape[1], "(= 2*emb + raw)")
prob, _ = run_xgb(A_tr, y[tr_mask], A_va, y[va_mask], A_te, y[te_mask], "A: account-graph + XGB")
report("2b · Account-graph + XGB", y[te_mask], prob)

Approach-A XGB feature dim: 525 (= 2*emb + raw)
  [A: account-graph + XGB] best_iter = 77
  >>> [2b · Account-graph + XGB]  test ROC-AUC = 0.9600 | test PR-AUC (AP) = 0.3721

(np.float64(0.9599818732974571), np.float64(0.372083589791324))

## 5 · Approach B — Transaction-level graph (YOUR GTAN architecture)

This is a faithful port of your reference-node GTAN notebook, adapted to AML:

* **Nodes = transactions**, features = the standardized tabular matrix `X_std`.
* **Identity-chain edges**: transactions sharing the same `from_id` (relation 0)
  or `to_id` (relation 1) are chained in time with `_chain_pairs`
  (`EDGE_PER_TRANS` steps). These replace the `uid` / `card1_addr1` chains.
* **Optional kNN cosine edges** (relation 4) — auto-off above `SIM_MAX_NODES`.
* **11-dim `edge_attr`**: 3 recency-decay channels, 5 relation flags, a
  self-loop flag, a relation count, and cosine — identical layout to your
  notebook. Top-k pruning per destination + weighted neighbour sampling.
* **`GTANEdge`** = your label-aware `TransformerConv` stack.
* **Reference-node label protocol** with reference-safe embedding extraction
  (set `LABEL_PROTOCOL="full"` to reveal all train labels instead).

The cell below defines the helpers (verbatim structure from your notebook); the
next cell builds the graph and trains.

In [95]:
# ===== Approach B — GTAN helpers (ported from your reference-node notebook) =====
REL_INDEX = {"from_id": 0, "to_id": 1, "similarity": 4}   # 5 relation-flag slots; AML uses 0,1,4

def _valid_id(v):
    v = np.asarray(v); ok = v != -1
    if np.issubdtype(v.dtype, np.floating): ok &= ~np.isnan(v)
    return ok

def _chain_pairs(labels, timestamps, edge_per_trans, valid=None):
    positions = np.arange(len(labels), dtype=np.int64)
    groups = np.asarray(labels); times_local = np.asarray(timestamps)
    if valid is not None:
        positions, groups, times_local = positions[valid], groups[valid], times_local[valid]
    if len(positions) == 0:
        empty = np.array([], dtype=np.int64); return empty, empty
    order = np.argsort(times_local, kind="mergesort")
    frame = pd.DataFrame({"node": positions[order], "group": groups[order]})
    src_list, dst_list = [], []
    for _, gframe in frame.groupby("group", sort=False):
        idx = gframe["node"].to_numpy(); glen = len(idx)
        for step in range(1, edge_per_trans):
            if step >= glen: break
            src_list.append(idx[:glen - step]); dst_list.append(idx[step:])
    if src_list: return np.concatenate(src_list), np.concatenate(dst_list)
    empty = np.array([], dtype=np.int64); return empty, empty

@torch.no_grad()
def knn_sim(X_norm_np, timestamps, uid_codes_np, k, dev, batch=512):
    n = X_norm_np.shape[0]
    Xn = torch.from_numpy(X_norm_np).to(dev)
    tt = torch.tensor(timestamps, device=dev)
    uc = torch.tensor(uid_codes_np, device=dev)
    src_parts, dst_parts = [], []
    for start in range(0, n, batch):
        end = min(start + batch, n)
        sims = Xn[start:end] @ Xn.T
        qt = tt[start:end].unsqueeze(1); qu = uc[start:end].unsqueeze(1)
        valid = (tt.unsqueeze(0) < qt) & (uc.unsqueeze(0) != qu)
        sims = sims.masked_fill(~valid, float("-inf"))
        kk = min(k, n)
        tv, ti = torch.topk(sims, kk, dim=1)
        mask = torch.isfinite(tv)
        rows = torch.arange(end - start, device=dev).unsqueeze(1).expand(-1, kk)[mask] + start
        cols = ti[mask]
        dst_parts.append(rows.cpu()); src_parts.append(cols.cpu())
        del sims, valid, tv, ti
    if dev.type == "cuda": torch.cuda.empty_cache()
    if not src_parts:
        empty = np.array([], dtype=np.int64); return empty, empty
    return torch.cat(src_parts).numpy(), torch.cat(dst_parts).numpy()

def prune_topk_per_destination(edge_index, edge_attr, k):
    dst = edge_index[1].cpu().numpy()
    cosine = edge_attr[:, 10].cpu().numpy()
    strength = cosine + edge_attr[:, 9].cpu().numpy() + edge_attr[:, 1].cpu().numpy()
    is_self = edge_attr[:, 8].cpu().numpy() > 0.5
    frame = pd.DataFrame({"dst": dst, "strength": strength, "edge": np.arange(len(dst))})
    frame["rank"] = frame.groupby("dst", sort=False)["strength"].rank(method="first", ascending=False)
    keep = (frame["rank"].to_numpy() <= k) | is_self
    selected = frame["edge"].to_numpy()[keep]
    return edge_index[:, selected], edge_attr[selected]

def build_aml_edges(features, identities, timestamps):
    n = features.shape[0]
    norm = np.linalg.norm(features, axis=1, keepdims=True); norm[norm == 0] = 1.0
    features_norm = (features / norm).astype(np.float32)
    parts = []
    for column in IDENTITY_COLS:
        vals = identities[column]
        src, dst = _chain_pairs(vals, timestamps, EDGE_PER_TRANS, valid=_valid_id(vals))
        if len(src):
            parts.append((src, dst, REL_INDEX[column])); print(f"    {column}: {len(src):,} edges")
    use_sim = USE_SIMILARITY_EDGES and n <= SIM_MAX_NODES
    if use_sim:
        src, dst = knn_sim(features_norm, timestamps, identities["from_id"], K_SIM, device, SIM_BATCH)
        if len(src):
            parts.append((src, dst, REL_INDEX["similarity"])); print(f"    similarity(kNN k={K_SIM}): {len(src):,} edges")
    else:
        print(f"    similarity edges: DISABLED (N={n:,} > SIM_MAX_NODES={SIM_MAX_NODES:,} or flag off)")

    if parts:
        src_all = np.concatenate([p[0] for p in parts]); dst_all = np.concatenate([p[1] for p in parts])
        rel_all = np.concatenate([np.full(len(p[0]), p[2], np.int8) for p in parts])
        frame = pd.DataFrame({"src": src_all, "dst": dst_all})
        for rid in range(5): frame[f"r{rid}"] = (rel_all == rid).astype(np.float32)
        grouped = frame.groupby(["src", "dst"], sort=False).max().reset_index()
        src = grouped["src"].to_numpy(); dst = grouped["dst"].to_numpy()
        relation_flags = grouped[[f"r{i}" for i in range(5)]].to_numpy(np.float32)
        relation_count = relation_flags.sum(1, keepdims=True)
        delta_days = ((timestamps[dst] - timestamps[src]).astype(np.float32)) / 86400.0
        recency = np.stack([np.exp(-delta_days / float(t)) for t in DECAY_TAUS], 1).astype(np.float32)
        cosine = np.empty((len(src), 1), np.float32)
        chunk = 1_000_000
        for s0 in range(0, len(src), chunk):
            s1 = min(s0 + chunk, len(src))
            cosine[s0:s1, 0] = (features_norm[src[s0:s1]] * features_norm[dst[s0:s1]]).sum(1)
        edge_attr_np = np.concatenate(
            [recency, relation_flags, np.zeros((len(src), 1), np.float32), relation_count, cosine], 1
        ).astype(np.float32)
        edge_index = torch.tensor(np.stack([src, dst]), dtype=torch.long)
        edge_attr = torch.tensor(edge_attr_np)
    else:
        edge_index = torch.empty((2, 0), dtype=torch.long); edge_attr = torch.zeros((0, 11), torch.float32)

    loops = torch.arange(n, dtype=torch.long)
    self_attr = torch.zeros((n, 11), dtype=torch.float32)
    self_attr[:, 0:3] = 1.0; self_attr[:, 8] = 1.0; self_attr[:, 10] = 1.0
    edge_index = torch.cat([edge_index, torch.stack([loops, loops])], 1)
    edge_attr = torch.cat([edge_attr, self_attr], 0)
    print(f"    total edges incl self-loops: {edge_index.shape[1]:,}; edge_dim={edge_attr.shape[1]}")
    return edge_index, edge_attr

def _make_y_input(y, known_idx, n_classes=2):
    y_input = torch.full((len(y),), n_classes, dtype=torch.long)
    if len(known_idx):
        idx = torch.as_tensor(known_idx, dtype=torch.long); y_input[idx] = y.cpu()[idx]
    return y_input

class GTANEdge(nn.Module):
    def __init__(self, in_feats, hidden_dim=32, heads=4, n_layers=2, n_classes=2, dropout=0.2, edge_dim=11):
        super().__init__()
        self.n_classes = n_classes; width = hidden_dim * heads
        self.label_emb = nn.Embedding(n_classes + 1, in_feats, padding_idx=n_classes)
        self.feat_lin = nn.Linear(in_feats, width); self.label_lin = nn.Linear(in_feats, width)
        self.label_proc = nn.Sequential(nn.BatchNorm1d(width), nn.PReLU(), nn.Dropout(dropout),
                                        nn.Linear(width, in_feats))
        self.input_drop = nn.Dropout(dropout)
        self.convs = nn.ModuleList(); self.norms = nn.ModuleList(); dim = in_feats
        for _ in range(n_layers):
            self.convs.append(TransformerConv(dim, hidden_dim, heads=heads, concat=True, beta=True,
                                              dropout=dropout, edge_dim=edge_dim))
            self.norms.append(nn.LayerNorm(width)); dim = width
        self.act = nn.PReLU(); self.drop = nn.Dropout(dropout); self.emb_dim = dim
        self.head = nn.Sequential(nn.Linear(dim, dim), nn.BatchNorm1d(dim), nn.PReLU(),
                                  nn.Dropout(dropout), nn.Linear(dim, n_classes))
    def forward(self, x, edge_index, y_input, edge_attr=None):
        labels = self.input_drop(self.label_emb(y_input))
        hidden = x + self.label_proc(self.feat_lin(x) + self.label_lin(labels))
        for conv, norm in zip(self.convs, self.norms):
            hidden = self.drop(self.act(norm(conv(hidden, edge_index, edge_attr=edge_attr))))
        return self.head(hidden), hidden

def _loader(x, edge_index, edge_attr, sampling_weight, y_input, input_nodes, batch_size, neighbors, shuffle, y=None):
    data = Data(x=x.cpu().float(), edge_index=edge_index.cpu())
    data.edge_attr = edge_attr.cpu().float()
    if sampling_weight is not None: data.edge_weight = sampling_weight.cpu().float()
    data.yik = y_input.cpu().long()
    if y is not None: data.y = y.cpu().long()
    kwargs = {}
    if USE_WEIGHTED_SAMPLING: kwargs["weight_attr"] = "edge_weight"
    try:
        return NeighborLoader(data, num_neighbors=list(neighbors), input_nodes=torch.as_tensor(input_nodes),
                              batch_size=batch_size, shuffle=shuffle, **kwargs)
    except Exception as e:
        print(f"  [loader] {type(e).__name__}; uniform sampling fallback")
        return NeighborLoader(data, num_neighbors=list(neighbors), input_nodes=torch.as_tensor(input_nodes),
                              batch_size=batch_size, shuffle=shuffle)

def _mask_seed_labels(y_input_batch, seed_count):
    y = y_input_batch.clone(); y[:seed_count] = 2; return y

print("GTAN helpers ready")

GTAN helpers ready

In [96]:
# ===== Approach B — reference selection, training, leakage-safe embeddings =====
def select_reference_and_query(train_idx, uid_values, seed):
    train_idx = np.asarray(train_idx, dtype=np.int64)
    if LABEL_PROTOCOL == "full" or REF_FRAC <= 0:
        return train_idx.copy(), train_idx.copy()   # reveal all train labels
    rng = np.random.default_rng(seed)
    uid = np.asarray(uid_values)
    train_uids = uid[train_idx]; valid = _valid_id(train_uids)
    cand = pd.unique(train_uids[valid])
    if len(cand):
        n_ref = min(len(cand), max(1, int(round(REF_FRAC * len(cand)))))
        ref_uids = rng.permutation(cand)[:n_ref]
        reference_idx = train_idx[np.isin(train_uids, ref_uids)]
    else:
        n_ref = min(len(train_idx), max(1, int(round(REF_FRAC * len(train_idx)))))
        reference_idx = np.sort(rng.permutation(train_idx)[:n_ref])
    query_idx = np.setdiff1d(train_idx, reference_idx, assume_unique=False)
    if len(query_idx) == 0: query_idx = train_idx.copy()
    return np.asarray(reference_idx, np.int64), np.asarray(query_idx, np.int64)

def train_gtan_edge(x, edge_index, edge_attr, y, query_idx, val_idx, reference_idx, in_feats, dev, verbose=True):
    y_cpu = y.cpu()
    query_idx = np.asarray(query_idx, np.int64); val_idx = np.asarray(val_idx, np.int64)
    reference_idx = np.asarray(reference_idx, np.int64)
    pos = float((y_cpu[torch.as_tensor(query_idx)] == 1).sum().clamp(min=1))
    neg = float((y_cpu[torch.as_tensor(query_idx)] == 0).sum().clamp(min=1))
    class_weight = torch.tensor([1.0, float(np.sqrt(neg / pos))], device=dev)
    sampling_weight = None
    if USE_WEIGHTED_SAMPLING:
        cosine = edge_attr[:, 10].clamp(0, 1)
        sampling_weight = (edge_attr[:, 9] + edge_attr[:, 1] + cosine + 1e-3).float()
    model = GTANEdge(in_feats, GTAN_HIDDEN, GTAN_HEADS, GTAN_LAYERS, 2, GTAN_DROP,
                     edge_dim=edge_attr.shape[1]).to(dev)
    opt = torch.optim.Adam(model.parameters(), lr=GTAN_LR, weight_decay=GTAN_WD)
    y_input = _make_y_input(y_cpu, reference_idx)
    tl = _loader(x, edge_index, edge_attr, sampling_weight, y_input, query_idx, GTAN_BATCH, GTAN_NEIGH, True, y=y)
    vl = _loader(x, edge_index, edge_attr, sampling_weight, y_input, val_idx, GTAN_BATCH, GTAN_NEIGH, False, y=y)
    best_auc, best_state, bad = -1.0, None, 0
    for ep in range(1, GTAN_EPOCHS + 1):
        model.train(); tot = nb = 0
        for b in tl:
            sc = b.batch_size; b = b.to(dev)
            opt.zero_grad()
            logits, _ = model(b.x, b.edge_index, _mask_seed_labels(b.yik, sc), b.edge_attr)
            loss = F.cross_entropy(logits[:sc], b.y[:sc], weight=class_weight)
            loss.backward(); nn.utils.clip_grad_norm_(model.parameters(), 2.0); opt.step()
            tot += float(loss); nb += 1
        model.eval(); vp = np.zeros(y.shape[0], np.float32)
        with torch.no_grad():
            for b in vl:
                sc = b.batch_size; b = b.to(dev)
                logits, _ = model(b.x, b.edge_index, b.yik, b.edge_attr)
                vp[b.n_id[:sc].cpu().numpy()] = F.softmax(logits[:sc], 1)[:, 1].cpu().numpy()
        va = roc_auc_score(y_cpu.numpy()[val_idx], vp[val_idx])
        if va > best_auc + GTAN_EARLY_STOP_MIN_DELTA:
            best_auc, best_state, bad = va, {k: v.detach().clone() for k, v in model.state_dict().items()}, 0
        else: bad += 1
        if verbose: print(f"   ep {ep:2d}/{GTAN_EPOCHS} loss={tot/max(nb,1):.4f} val_auc={va:.4f} best={best_auc:.4f}")
        if GTAN_EARLY_STOP_PATIENCE and bad >= GTAN_EARLY_STOP_PATIENCE:
            print(f"   early stop at epoch {ep}"); break
    if best_state: model.load_state_dict(best_state)
    print(f"   >>> GTAN best val AUC = {best_auc:.4f}")
    return model, sampling_weight

@torch.no_grad()
def _predict(model, x, edge_index, edge_attr, sampling_weight, y_input, input_nodes, dev):
    model.eval(); input_nodes = np.asarray(input_nodes, np.int64)
    prob = np.zeros(x.shape[0], np.float32); emb = np.zeros((x.shape[0], model.emb_dim), np.float32)
    loader = _loader(x, edge_index, edge_attr, sampling_weight, y_input, input_nodes, GTAN_BATCH, GTAN_NEIGH, False)
    for b in loader:
        sc = b.batch_size; b = b.to(dev)
        logits, hidden = model(b.x, b.edge_index, b.yik, b.edge_attr)
        nid = b.n_id[:sc].cpu().numpy()
        prob[nid] = F.softmax(logits[:sc], 1)[:, 1].cpu().numpy()
        emb[nid] = hidden[:sc].cpu().numpy()
    return prob, emb

def reference_safe_embeddings(model, x, edge_index, edge_attr, sampling_weight, y, reference_idx, dev):
    # Every non-reference node is scored with reference labels revealed (own label
    # masked); reference nodes are scored out-of-fold so their own label never leaks.
    n = x.shape[0]; prob = np.zeros(n, np.float32); emb = np.zeros((n, model.emb_dim), np.float32)
    reference_idx = np.asarray(reference_idx, np.int64)
    other = np.setdiff1d(np.arange(n), reference_idx, assume_unique=False)
    base_y = _make_y_input(y.cpu(), reference_idx)
    p, e = _predict(model, x, edge_index, edge_attr, sampling_weight, base_y, other, dev)
    prob[other] = p[other]; emb[other] = e[other]
    if len(reference_idx):
        rng = np.random.default_rng(REF_SEED); shuffled = rng.permutation(reference_idx)
        for held in np.array_split(shuffled, REFERENCE_OOF_FOLDS):
            if len(held) == 0: continue
            revealed = np.setdiff1d(reference_idx, held, assume_unique=False)
            hy = _make_y_input(y.cpu(), revealed)
            p, e = _predict(model, x, edge_index, edge_attr, sampling_weight, hy, held, dev)
            prob[held] = p[held]; emb[held] = e[held]
    return prob, emb

print("GTAN train / embedding routines ready")

GTAN train / embedding routines ready

### 5a · Approach B — build graph, train GTAN (graph alone)

One graph is built over **all** sub-sampled transactions (edges use only
timestamps + shared accounts, never labels). Training supervises the query-train
nodes, early-stops on val, and reports test. Edges always run earlier→later in
time, so a node only ever aggregates from its past → temporally valid.

In [97]:
# ===== Approach B — build graph + train =====
node_idx = np.arange(len(tx))
train_local = node_idx[tr_mask]; val_local = node_idx[va_mask]; test_local = node_idx[te_mask]
identities = {c: pd.factorize(tx[c].to_numpy())[0] for c in IDENTITY_COLS}

print("building transaction graph ...")
B_edge_index, B_edge_attr = build_aml_edges(X_std, identities, time_arr)
if PRUNE_TOPK:
    before = B_edge_index.shape[1]
    B_edge_index, B_edge_attr = prune_topk_per_destination(B_edge_index, B_edge_attr, PRUNE_K)
    print(f"    top-{PRUNE_K} prune: {before:,} -> {B_edge_index.shape[1]:,} edges")

reference_local, query_local = select_reference_and_query(train_local, identities["from_id"], REF_SEED)
print(f"label protocol = {LABEL_PROTOCOL} | reference={len(reference_local):,} query={len(query_local):,} "
      f"val={len(val_local):,} test={len(test_local):,}")

xB = torch.tensor(X_std)
yB = torch.tensor(y, dtype=torch.long)
gtan_model, B_sw = train_gtan_edge(xB, B_edge_index, B_edge_attr, yB,
                                   query_local, val_local, reference_local, NF, device, verbose=True)

# graph-alone test predictions: test nodes are scored with reference labels revealed
test_y_input = _make_y_input(yB.cpu(), reference_local)
B_prob, _ = _predict(gtan_model, xB, B_edge_index, B_edge_attr, B_sw, test_y_input, test_local, device)
report("3a · GTAN (transaction-graph) alone", y[te_mask], B_prob[test_local])

building transaction graph ...
    from_id: 766,162 edges
    to_id: 547,030 edges
    similarity(kNN k=15): 7,484,070 edges
    total edges incl self-loops: 9,060,683; edge_dim=11
    top-15 prune: 9,060,683 -> 7,984,102 edges
label protocol = reference | reference=141,447 query=208,583 val=74,981 test=74,989
   ep  1/15 loss=0.2472 val_auc=0.9394 best=0.9394
   ep  2/15 loss=0.1578 val_auc=0.9511 best=0.9511
   ep  3/15 loss=0.1432 val_auc=0.9587 best=0.9587
   ep  4/15 loss=0.1381 val_auc=0.9590 best=0.9590
   ep  5/15 loss=0.1337 val_auc=0.9614 best=0.9614
   ep  6/15 loss=0.1292 val_auc=0.9647 best=0.9647
   ep  7/15 loss=0.1266 val_auc=0.9627 best=0.9647
   ep  8/15 loss=0.1228 val_auc=0.9667 best=0.9667
   ep  9/15 loss=0.1226 val_auc=0.9681 best=0.9681
   ep 10/15 loss=0.1210 val_auc=0.9686 best=0.9686
   ep 11/15 loss=0.1184 val_auc=0.9682 best=0.9686
   ep 12/15 loss=0.1171 val_auc=0.9688 best=0.9688
   ep 13/15 loss=0.1149 val_auc=0.9707 best=0.9707
   ep 14/15 loss=0.1136 val_auc=0.9693 best=0.9707
   ep 15/15 loss=0.1127 val_auc=0.9708 best=0.9707
   >>> GTAN best val AUC = 0.9707
  >>> [3a · GTAN (transaction-graph) alone]  test ROC-AUC = 0.9765 | test PR-AUC (AP) = 0.5544

(np.float64(0.976471074797179), np.float64(0.5543947899737077))

### 5b · Approach B — Graph + XGBoost

Extract **leakage-safe** GTAN node embeddings for every transaction
(`reference_safe_embeddings`), standardize them on the train rows, concatenate
with the raw tabular features, and feed XGBoost.

In [98]:
# ===== Approach B — GTAN embeddings + XGBoost =====
print("extracting reference-safe GTAN embeddings ...")
_, B_emb = reference_safe_embeddings(gtan_model, xB, B_edge_index, B_edge_attr, B_sw, yB, reference_local, device)
emu = B_emb[tr_mask].mean(0); esd = B_emb[tr_mask].std(0) + 1e-6
B_emb_std = ((B_emb - emu) / esd).astype(np.float32)
B_feats = np.concatenate([B_emb_std, X_raw], axis=1).astype(np.float32)
print("Approach-B XGB feature dim:", B_feats.shape[1], "(= gtan_emb + raw)")
prob, _ = run_xgb(B_feats[tr_mask], y[tr_mask], B_feats[va_mask], y[va_mask],
                  B_feats[te_mask], y[te_mask], "B: GTAN + XGB")
report("3b · GTAN + XGB", y[te_mask], prob)

extracting reference-safe GTAN embeddings ...
Approach-B XGB feature dim: 141 (= gtan_emb + raw)
  [B: GTAN + XGB] best_iter = 162
  >>> [3b · GTAN + XGB]  test ROC-AUC = 0.9749 | test PR-AUC (AP) = 0.4931

(np.float64(0.9749107501717166), np.float64(0.49306600065169015))

## 6 · Summary — all five runs on the same test set

ROC-AUC is optimistic under 0.1–1 % prevalence, so **PR-AUC (AP)** is the
metric to trust for ranking the models.

In [99]:
# ===== Summary table =====
order = ["1 · XGBoost alone",
         "2a · Account-graph alone", "2b · Account-graph + XGB",
         "3a · GTAN (transaction-graph) alone", "3b · GTAN + XGB"]
summary = pd.DataFrame(
    [{"experiment": k, "test_ROC_AUC": round(RESULTS[k]["test_auc"], 4),
      "test_PR_AUC": round(RESULTS[k]["test_ap"], 4)} for k in order if k in RESULTS]
)
print(summary.to_string(index=False))
summary

                         experiment  test_ROC_AUC  test_PR_AUC
                  1 · XGBoost alone        0.9730       0.5473
           2a · Account-graph alone        0.8476       0.1506
           2b · Account-graph + XGB        0.9600       0.3721
3a · GTAN (transaction-graph) alone        0.9765       0.5544
                    3b · GTAN + XGB        0.9749       0.4931

                            experiment  test_ROC_AUC  test_PR_AUC
0                    1 · XGBoost alone        0.9730       0.5473
1             2a · Account-graph alone        0.8476       0.1506
2             2b · Account-graph + XGB        0.9600       0.3721
3  3a · GTAN (transaction-graph) alone        0.9765       0.5544
4                      3b · GTAN + XGB        0.9749       0.4931